// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CalculationMethodId.
const (
	Egypt             CalculationMethodId = "egypt"
	Karachi           CalculationMethodId = "karachi"
	MuslimWorldLeague CalculationMethodId = "muslimWorldLeague"
	NorthAmerica      CalculationMethodId = "northAmerica"
	Turkey            CalculationMethodId = "turkey"
	UmmAlQura         CalculationMethodId = "ummAlQura"
)

// Valid indicates whether the value is a known member of the CalculationMethodId enum.
func (e CalculationMethodId) Valid() bool {
	switch e {
	case Egypt:
		return true
	case Karachi:
		return true
	case MuslimWorldLeague:
		return true
	case NorthAmerica:
		return true
	case Turkey:
		return true
	case UmmAlQura:
		return true
	default:
		return false
	}
}

// Defines values for ConfirmationStatus.
const (
	Confirmed ConfirmationStatus = "confirmed"
	Expected  ConfirmationStatus = "expected"
)

// Valid indicates whether the value is a known member of the ConfirmationStatus enum.
func (e ConfirmationStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Expected:
		return true
	default:
		return false
	}
}

// Defines values for DeviceRegistrationPlatform.
const (
	Ios DeviceRegistrationPlatform = "ios"
)

// Valid indicates whether the value is a known member of the DeviceRegistrationPlatform enum.
func (e DeviceRegistrationPlatform) Valid() bool {
	switch e {
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeInternal        ErrorCode = "internal"
	ErrorCodeInvalidArgument ErrorCode = "invalid_argument"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRateLimited     ErrorCode = "rate_limited"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
	ErrorCodeUnsupported     ErrorCode = "unsupported"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidArgument:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for IshaRuleType.
const (
	Angle               IshaRuleType = "angle"
	MinutesAfterMaghrib IshaRuleType = "minutesAfterMaghrib"
)

// Valid indicates whether the value is a known member of the IshaRuleType enum.
func (e IshaRuleType) Valid() bool {
	switch e {
	case Angle:
		return true
	case MinutesAfterMaghrib:
		return true
	default:
		return false
	}
}

// Defines values for Madhab.
const (
	Hanafi Madhab = "hanafi"
	Shafii Madhab = "shafii"
)

// Valid indicates whether the value is a known member of the Madhab enum.
func (e Madhab) Valid() bool {
	switch e {
	case Hanafi:
		return true
	case Shafii:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSource.
const (
	PrayerSourceCalculated PrayerSource = "calculated"
	PrayerSourceOfficial   PrayerSource = "official"
)

// Valid indicates whether the value is a known member of the PrayerSource enum.
func (e PrayerSource) Valid() bool {
	switch e {
	case PrayerSourceCalculated:
		return true
	case PrayerSourceOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSourceParam.
const (
	PrayerSourceParamAuto       PrayerSourceParam = "auto"
	PrayerSourceParamCalculated PrayerSourceParam = "calculated"
	PrayerSourceParamOfficial   PrayerSourceParam = "official"
)

// Valid indicates whether the value is a known member of the PrayerSourceParam enum.
func (e PrayerSourceParam) Valid() bool {
	switch e {
	case PrayerSourceParamAuto:
		return true
	case PrayerSourceParamCalculated:
		return true
	case PrayerSourceParamOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PushSettingsEnvironment.
const (
	Production PushSettingsEnvironment = "production"
	Sandbox    PushSettingsEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the PushSettingsEnvironment enum.
func (e PushSettingsEnvironment) Valid() bool {
	switch e {
	case Production:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// CalculationMethod defines model for CalculationMethod.
type CalculationMethod struct {
	// FajrAngle Example: 18
	FajrAngle float64 `json:"fajrAngle"`

	// Id Идентификаторы строго совпадают с CalculationMethod в iOS
	Id   CalculationMethodId `json:"id"`
	Isha IshaRule            `json:"isha"`

	// Title Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Title LocalizedString `json:"title"`
}

// CalculationMethodId Идентификаторы строго совпадают с CalculationMethod в iOS
type CalculationMethodId string

// CalculationMethodList defines model for CalculationMethodList.
type CalculationMethodList struct {
	Items []CalculationMethod `json:"items"`
}

// City defines model for City.
type City struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country              string `json:"country"`
	HasOfficialTimetable bool   `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// CityList defines model for CityList.
type CityList struct {
	Items      []City  `json:"items"`
	NextCursor *string `json:"nextCursor"`
}

// Config defines model for Config.
type Config struct {
	// ContentVersions Версии контента (quran, quranEditions, hadith, cities)
	//
	// Example: {"cities":7,"hadith":2,"quran":3,"quranEditions":5}
	ContentVersions map[string]int `json:"contentVersions"`
	Features        Features       `json:"features"`

	// LatestVersion Example: 1.0.3
	LatestVersion string `json:"latestVersion"`

	// MinSupportedVersion Example: 1.0.0
	MinSupportedVersion string          `json:"minSupportedVersion"`
	Ramadan             *RamadanSummary `json:"ramadan,omitempty"`

	// SupportUrl Example: https://namoz.tj/support
	SupportUrl string `json:"supportUrl"`
}

// ConfirmationStatus defines model for ConfirmationStatus.
type ConfirmationStatus string

// Coordinate defines model for Coordinate.
type Coordinate struct {
	// Latitude Example: 40.2826
	Latitude float64 `json:"latitude"`

	// Longitude Example: 69.6222
	Longitude float64 `json:"longitude"`
}

// DeviceCreated defines model for DeviceCreated.
type DeviceCreated struct {
	// DeviceId Example: dev_5f1c0a9e3b7d4c2a8e6f1b0d
	DeviceId string `json:"deviceId"`

	// Token Секрет устройства. Показывается один раз, на сервере хранится только хэш.
	Token string `json:"token"`
}

// DeviceRegistration defines model for DeviceRegistration.
type DeviceRegistration struct {
	// AppVersion Example: 1.0.0
	AppVersion string `json:"appVersion"`

	// Country Example: TJ
	Country *string `json:"country,omitempty"`

	// Locale Example: ru_TJ
	Locale   *string                    `json:"locale,omitempty"`
	Platform DeviceRegistrationPlatform `json:"platform"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId *string `json:"timeZoneId,omitempty"`
}

// DeviceRegistrationPlatform defines model for DeviceRegistration.Platform.
type DeviceRegistrationPlatform string

// Dua defines model for Dua.
type Dua struct {
	Arabic string `json:"arabic"`

	// Id Example: iftar
	Id string `json:"id"`

	// Source Example: Sunan Abi Dawud 2357
	Source *string `json:"source,omitempty"`

	// Translations Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Translations    LocalizedString `json:"translations"`
	Transliteration *string         `json:"transliteration,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    ErrorCode               `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Example: City not found
	Message string `json:"message"`

	// RequestId Example: 01J9ZK3M5Q8T2V4X6Y8Z0A1B2C
	RequestId string `json:"requestId"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Features defines model for Features.
type Features struct {
	OfficialTimetables bool `json:"officialTimetables"`
	QuranSearch        bool `json:"quranSearch"`
	Sync               bool `json:"sync"`
}

// HijriDate defines model for HijriDate.
type HijriDate struct {
	// Day Example: 18
	Day int `json:"day"`

	// Month Example: 4
	Month int `json:"month"`

	// MonthName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	MonthName *LocalizedString `json:"monthName,omitempty"`

	// Year Example: 1448
	Year int `json:"year"`
}

// IshaRule defines model for IshaRule.
type IshaRule struct {
	Type IshaRuleType `json:"type"`

	// Value Example: 17
	Value float64 `json:"value"`
}

// IshaRuleType defines model for IshaRule.Type.
type IshaRuleType string

// LocalizedString Локализуемая строка. Ключи — коды языков.
//
// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
type LocalizedString struct {
	Ar *string `json:"ar,omitempty"`
	En *string `json:"en,omitempty"`
	Ru *string `json:"ru,omitempty"`
	Tg *string `json:"tg,omitempty"`
}

// Madhab defines model for Madhab.
type Madhab string

// NearestCity defines model for NearestCity.
type NearestCity struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country string `json:"country"`

	// DistanceKm Example: 2.4
	DistanceKm           float64 `json:"distanceKm"`
	HasOfficialTimetable bool    `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// PrayerDay defines model for PrayerDay.
type PrayerDay struct {
	// Date Example: 2026-09-30
	Date  openapi_types.Date `json:"date"`
	Hijri HijriDate          `json:"hijri"`

	// Imsak Example: 2026-09-30T04:41:00+05:00
	Imsak *time.Time `json:"imsak,omitempty"`

	// Times Моменты времени в ISO 8601 со смещением часового пояса города
	Times PrayerTimes `json:"times"`
}

// PrayerSource defines model for PrayerSource.
type PrayerSource string

// PrayerSourceParam defines model for PrayerSourceParam.
type PrayerSourceParam string

// PrayerTimes Моменты времени в ISO 8601 со смещением часового пояса города
type PrayerTimes struct {
	// Asr Example: 2026-09-30T16:26:00+05:00
	Asr time.Time `json:"asr"`

	// Dhuhr Example: 2026-09-30T12:17:00+05:00
	Dhuhr time.Time `json:"dhuhr"`

	// Fajr Example: 2026-09-30T04:51:00+05:00
	Fajr time.Time `json:"fajr"`

	// Isha Example: 2026-09-30T19:33:00+05:00
	Isha time.Time `json:"isha"`

	// Maghrib Example: 2026-09-30T18:11:00+05:00
	Maghrib time.Time `json:"maghrib"`

	// Sunrise Example: 2026-09-30T06:20:00+05:00
	Sunrise time.Time `json:"sunrise"`
}

// PrayerTimesResponse defines model for PrayerTimesResponse.
type PrayerTimesResponse struct {
	// CityId null, если запрос был по координатам
	//
	// Example: dushanbe
	CityId *string     `json:"cityId,omitempty"`
	Days   []PrayerDay `json:"days"`
	Madhab Madhab      `json:"madhab"`

	// Method Идентификаторы строго совпадают с CalculationMethod в iOS
	Method CalculationMethodId `json:"method"`
	Source PrayerSource        `json:"source"`

	// SourceName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	SourceName *LocalizedString `json:"sourceName,omitempty"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`

	// UpdatedAt Example: 2026-09-01T00:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PushSettings defines model for PushSettings.
type PushSettings struct {
	// ApnsToken Токен APNs (hex)
	ApnsToken   string                  `json:"apnsToken"`
	Environment PushSettingsEnvironment `json:"environment"`

	// Topics Example: ["ramadan-TJ","eid-TJ","announcements"]
	Topics []string `json:"topics"`
}

// PushSettingsEnvironment defines model for PushSettings.Environment.
type PushSettingsEnvironment string

// Ramadan defines model for Ramadan.
type Ramadan struct {
	ConfirmedAt *time.Time `json:"confirmedAt,omitempty"`

	// Country Example: TJ
	Country string `json:"country"`
	Duas    []Dua  `json:"duas"`

	// EidAlFitr Example: 2027-03-10
	EidAlFitr openapi_types.Date `json:"eidAlFitr"`

	// EndDate Example: 2027-03-09
	EndDate openapi_types.Date `json:"endDate"`

	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// LaylatAlQadrExpected Example: 2027-03-05
	LaylatAlQadrExpected *openapi_types.Date `json:"laylatAlQadrExpected,omitempty"`

	// Length Example: 30
	Length int `json:"length"`

	// Source Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Source *LocalizedString `json:"source,omitempty"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// RamadanSummary defines model for RamadanSummary.
type RamadanSummary struct {
	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// AcceptLanguage Example: ru
type AcceptLanguage = string

// CityIdPath Example: dushanbe
type CityIdPath = string

// CountryQuery Example: TJ
type CountryQuery = string

// CountryRequired Example: TJ
type CountryRequired = string

// Cursor defines model for Cursor.
type Cursor = string

// LatQuery defines model for LatQuery.
type LatQuery = float64

// Limit defines model for Limit.
type Limit = int

// LonQuery defines model for LonQuery.
type LonQuery = float64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unsupported defines model for Unsupported.
type Unsupported = Error

// ListCitiesParams defines parameters for ListCities.
type ListCitiesParams struct {
	// Query Строка поиска («Худж», «Хуҷанд», «Khujand»)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Country Код страны ISO 3166-1 alpha-2
	Country *CountryQuery `form:"country,omitempty" json:"country,omitempty"`
	Limit   *Limit        `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор из nextCursor предыдущего ответа
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetNearestCityParams defines parameters for GetNearestCity.
type GetNearestCityParams struct {
	Lat LatQuery `form:"lat" json:"lat"`
	Lon LonQuery `form:"lon" json:"lon"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetCityParams defines parameters for GetCity.
type GetCityParams struct {
	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetPrayerTimesParams defines parameters for GetPrayerTimes.
type GetPrayerTimesParams struct {
	// CityId Идентификатор города. Обязателен, если не переданы lat/lon/timeZoneId.
	CityId *string  `form:"cityId,omitempty" json:"cityId,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Lon    *float64 `form:"lon,omitempty" json:"lon,omitempty"`

	// TimeZoneId IANA часовой пояс, обязателен вместе с lat/lon
	TimeZoneId *string            `form:"timeZoneId,omitempty" json:"timeZoneId,omitempty"`
	From       openapi_types.Date `form:"from" json:"from"`
	To         openapi_types.Date `form:"to" json:"to"`

	// Method По умолчанию — suggestedMethod города
	Method *CalculationMethodId `form:"method,omitempty" json:"method,omitempty"`

	// Madhab По умолчанию — suggestedMadhab города
	Madhab *Madhab            `form:"madhab,omitempty" json:"madhab,omitempty"`
	Source *PrayerSourceParam `form:"source,omitempty" json:"source,omitempty"`
}

// GetRamadanParams defines parameters for GetRamadan.
type GetRamadanParams struct {
	// Country Код страны ISO 3166-1 alpha-2
	Country CountryRequired `form:"country" json:"country"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistration

// SetDevicePushJSONRequestBody defines body for SetDevicePush for application/json ContentType.
type SetDevicePushJSONRequestBody = PushSettings

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(c *gin.Context)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(c *gin.Context, params ListCitiesParams)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(c *gin.Context, params GetNearestCityParams)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(c *gin.Context, cityId CityIdPath, params GetCityParams)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(c *gin.Context)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(c *gin.Context)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(c *gin.Context)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(c *gin.Context, params GetPrayerTimesParams)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(c *gin.Context, hijriYear int, params GetRamadanParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListCalculationMethods operation middleware
func (siw *ServerInterfaceWrapper) ListCalculationMethods(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCalculationMethods(c)
}

// ListCities operation middleware
func (siw *ServerInterfaceWrapper) ListCities(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCitiesParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", c.Request.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "country", c.Request.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter country: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Accept-Language, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Accept-Language: %w", err), http.StatusBadRequest)
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCities(c, params)
}

// GetNearestCity operation middleware
func (siw *ServerInterfaceWrapper) GetNearestCity(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearestCityParams

	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", c.Request.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lon", c.Request.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lon: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Accept-Language, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Accept-Language: %w", err), http.StatusBadRequest)
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNearestCity(c, params)
}

// GetCity operation middleware
func (siw *ServerInterfaceWrapper) GetCity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "cityId" -------------
	var cityId CityIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "cityId", c.Param("cityId"), &cityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cityId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCityParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Accept-Language, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Accept-Language: %w", err), http.StatusBadRequest)
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCity(c, cityId, params)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConfig(c)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterDevice(c)
}

// SetDevicePush operation middleware
func (siw *ServerInterfaceWrapper) SetDevicePush(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetDevicePush(c)
}

// GetPrayerTimes operation middleware
func (siw *ServerInterfaceWrapper) GetPrayerTimes(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPrayerTimesParams

	// ------------- Optional query parameter "cityId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cityId", c.Request.URL.Query(), &params.CityId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cityId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", c.Request.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lon", c.Request.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lon: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "timeZoneId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeZoneId", c.Request.URL.Query(), &params.TimeZoneId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeZoneId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", c.Request.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter method: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "madhab" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "madhab", c.Request.URL.Query(), &params.Madhab, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter madhab: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", c.Request.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter source: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPrayerTimes(c, params)
}

// GetRamadan operation middleware
func (siw *ServerInterfaceWrapper) GetRamadan(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "hijriYear" -------------
	var hijriYear int

	err = runtime.BindStyledParameterWithOptions("simple", "hijriYear", c.Param("hijriYear"), &hijriYear, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hijriYear: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRamadanParams

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", c.Request.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter country: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Accept-Language, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Accept-Language: %w", err), http.StatusBadRequest)
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRamadan(c, hijriYear, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/config", wrapper.GetConfig)
	router.GET(options.BaseURL+"/cities", wrapper.ListCities)
	router.GET(options.BaseURL+"/cities/nearest", wrapper.GetNearestCity)
	router.GET(options.BaseURL+"/cities/:cityId", wrapper.GetCity)
	router.GET(options.BaseURL+"/calculation-methods", wrapper.ListCalculationMethods)
	router.GET(options.BaseURL+"/prayer-times", wrapper.GetPrayerTimes)
	router.GET(options.BaseURL+"/ramadan/:hijriYear", wrapper.GetRamadan)
	router.POST(options.BaseURL+"/devices", wrapper.RegisterDevice)
	router.PUT(options.BaseURL+"/devices/me/push", wrapper.SetDevicePush)
}

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedResponseHeaders struct {
	RetryAfter *int
}
type RateLimitedJSONResponse struct {
	Body Error

	Headers RateLimitedResponseHeaders
}

type UnauthorizedJSONResponse Error

type UnsupportedJSONResponse Error

type ListCalculationMethodsRequestObject struct {
}

type ListCalculationMethodsResponseObject interface {
	VisitListCalculationMethodsResponse(w http.ResponseWriter) error
}

type ListCalculationMethods200JSONResponse CalculationMethodList

func (response ListCalculationMethods200JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCalculationMethods500JSONResponse struct{ InternalJSONResponse }

func (response ListCalculationMethods500JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCitiesRequestObject struct {
	Params ListCitiesParams
}

type ListCitiesResponseObject interface {
	VisitListCitiesResponse(w http.ResponseWriter) error
}

type ListCities200JSONResponse CityList

func (response ListCities200JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities400JSONResponse struct{ BadRequestJSONResponse }

func (response ListCities400JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListCities429JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities500JSONResponse struct{ InternalJSONResponse }

func (response ListCities500JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCityRequestObject struct {
	Params GetNearestCityParams
}

type GetNearestCityResponseObject interface {
	VisitGetNearestCityResponse(w http.ResponseWriter) error
}

type GetNearestCity200JSONResponse NearestCity

func (response GetNearestCity200JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity400JSONResponse struct{ BadRequestJSONResponse }

func (response GetNearestCity400JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetNearestCity404JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity500JSONResponse struct{ InternalJSONResponse }

func (response GetNearestCity500JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCityRequestObject struct {
	CityId CityIdPath `json:"cityId"`
	Params GetCityParams
}

type GetCityResponseObject interface {
	VisitGetCityResponse(w http.ResponseWriter) error
}

type GetCity200JSONResponse City

func (response GetCity200JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCity404JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity500JSONResponse struct{ InternalJSONResponse }

func (response GetCity500JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfig500JSONResponse struct{ InternalJSONResponse }

func (response GetConfig500JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice201JSONResponse DeviceCreated

func (response RegisterDevice201JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice500JSONResponse struct{ InternalJSONResponse }

func (response RegisterDevice500JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePushRequestObject struct {
	Body *SetDevicePushJSONRequestBody
}

type SetDevicePushResponseObject interface {
	VisitSetDevicePushResponse(w http.ResponseWriter) error
}

type SetDevicePush204Response struct {
}

func (response SetDevicePush204Response) VisitSetDevicePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetDevicePush400JSONResponse struct{ BadRequestJSONResponse }

func (response SetDevicePush400JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SetDevicePush401JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush500JSONResponse struct{ InternalJSONResponse }

func (response SetDevicePush500JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimesRequestObject struct {
	Params GetPrayerTimesParams
}

type GetPrayerTimesResponseObject interface {
	VisitGetPrayerTimesResponse(w http.ResponseWriter) error
}

type GetPrayerTimes200JSONResponse PrayerTimesResponse

func (response GetPrayerTimes200JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPrayerTimes400JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPrayerTimes404JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes422JSONResponse struct{ UnsupportedJSONResponse }

func (response GetPrayerTimes422JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetPrayerTimes429JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes500JSONResponse struct{ InternalJSONResponse }

func (response GetPrayerTimes500JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadanRequestObject struct {
	HijriYear int `json:"hijriYear"`
	Params    GetRamadanParams
}

type GetRamadanResponseObject interface {
	VisitGetRamadanResponse(w http.ResponseWriter) error
}

type GetRamadan200JSONResponse Ramadan

func (response GetRamadan200JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRamadan400JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRamadan404JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan500JSONResponse struct{ InternalJSONResponse }

func (response GetRamadan500JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(ctx context.Context, request ListCalculationMethodsRequestObject) (ListCalculationMethodsResponseObject, error)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(ctx context.Context, request ListCitiesRequestObject) (ListCitiesResponseObject, error)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(ctx context.Context, request GetNearestCityRequestObject) (GetNearestCityResponseObject, error)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(ctx context.Context, request GetCityRequestObject) (GetCityResponseObject, error)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(ctx context.Context, request SetDevicePushRequestObject) (SetDevicePushResponseObject, error)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(ctx context.Context, request GetPrayerTimesRequestObject) (GetPrayerTimesResponseObject, error)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(ctx context.Context, request GetRamadanRequestObject) (GetRamadanResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListCalculationMethods operation middleware
func (sh *strictHandler) ListCalculationMethods(ctx *gin.Context) {
	var request ListCalculationMethodsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalculationMethods(ctx, request.(ListCalculationMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalculationMethods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListCalculationMethodsResponseObject); ok {
		if err := validResponse.VisitListCalculationMethodsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCities operation middleware
func (sh *strictHandler) ListCities(ctx *gin.Context, params ListCitiesParams) {
	var request ListCitiesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListCities(ctx, request.(ListCitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCities")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListCitiesResponseObject); ok {
		if err := validResponse.VisitListCitiesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNearestCity operation middleware
func (sh *strictHandler) GetNearestCity(ctx *gin.Context, params GetNearestCityParams) {
	var request GetNearestCityRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetNearestCity(ctx, request.(GetNearestCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNearestCity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetNearestCityResponseObject); ok {
		if err := validResponse.VisitGetNearestCityResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCity operation middleware
func (sh *strictHandler) GetCity(ctx *gin.Context, cityId CityIdPath, params GetCityParams) {
	var request GetCityRequestObject

	request.CityId = cityId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCity(ctx, request.(GetCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetCityResponseObject); ok {
		if err := validResponse.VisitGetCityResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(ctx *gin.Context) {
	var request GetConfigRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(ctx *gin.Context) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetDevicePush operation middleware
func (sh *strictHandler) SetDevicePush(ctx *gin.Context) {
	var request SetDevicePushRequestObject

	var body SetDevicePushJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetDevicePush(ctx, request.(SetDevicePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetDevicePush")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SetDevicePushResponseObject); ok {
		if err := validResponse.VisitSetDevicePushResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPrayerTimes operation middleware
func (sh *strictHandler) GetPrayerTimes(ctx *gin.Context, params GetPrayerTimesParams) {
	var request GetPrayerTimesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPrayerTimes(ctx, request.(GetPrayerTimesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPrayerTimes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPrayerTimesResponseObject); ok {
		if err := validResponse.VisitGetPrayerTimesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRamadan operation middleware
func (sh *strictHandler) GetRamadan(ctx *gin.Context, hijriYear int, params GetRamadanParams) {
	var request GetRamadanRequestObject

	request.HijriYear = hijriYear
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRamadan(ctx, request.(GetRamadanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRamadan")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRamadanResponseObject); ok {
		if err := validResponse.VisitGetRamadanResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FxbcxvHlf4rXbN5oEqDKymKQtU+0JKdZSzJsihnV5a0riamCYw0F3imRxHDQhVJWZZdjK1y4qp1OYlj",
	"J7vlh93aQDQhQbxAVf4F3fvkfc0v2erTPTdMgwBpSeu8SMSgp/v06XP6fOfr01g3mr7b8T3i0dBorBtt",
	"gi0SwJ9XCQ3WFlcpCcQni4TNwO5Q2/eMhsG+ZX2+wfrsKeKbbI8N2T7/jfhffOyzPX6fHbJdxA7YkD1h",
	"h2yI2HM2ZDt8iw35BhvwLf4bxJ6yHnvON9iQbxqmETbbxMViLLrWIUbDsD1KWiQwut2uaXRwgF1ClWyL",
	"zSbp0IvYa0W4RTTy/ZU95dtsD72zVOJbINGmGJvtoBnaMlEQmYh4JsLBqTJi/y7kZ4/5J2wP/W3jc0S8",
	"smEatuhI6sMwDQ+7QiY5cCkZOSs2uYfdjiNaBZFhxrMIaWB7LUPM4bxN15asK5i2RXPovyM+JL03oYFh",
	"GgF5P7IDYhkNGkREP4gVhW3srRD9UH7k0WDt7YgEaxr1fMmGbBcJnfAN1mOHfBstLb+FZmvz86Uawk6n",
	"jUv1WAfvQyepkLLrMVO/9gtDLBalJBDv/uuNxdK7t9br3Z8dJebVZLovSdJp9HlMyaMg9HWe8UfWl0bN",
	"ngqJ+UMhM3uGhFPwDb4pHACxAXuKPHKPym4QvNFnu3yb7fL7/GPWZ98JpxnyLbbD+nyL9cbNUcqhcZ+M",
	"sBcxTSxB14mD6ZFKWvUDF1Nhc3604giLc/E9241co3Guahqu7ckPJfFJDe9F7go4r2lctF2bjh0bvsyO",
	"ZpFVHDnUaJypZgaqV7Mj1cziLmEaF33v6Hn63knnWVvITRQ+js60K/oOO74XEtilXsOWsGwSwuSbvkeJ",
	"B3/iTsexm1iYTOV2KOxmPSPFzwKyajSMf6ikW3NFfhtWXg8CXw2lsbsd2JWVvT1nPXCZA2E/fAPN2N5d",
	"7NjWezhoRS7x6CmjaxpLnrB37LwCCb/iH7EBe8z2WA/CBN9QAveEbFIMkOmyT9/wI896BTJ9zfp8Uzom",
	"YoesL/7psWdsl/XZIZrxfPreqhAF5LqKKQFbJq9CtD/BlrDDt/lHIAzbZwN2IGJnLnLKoBZgSt5zpGyn",
	"DLMQx0tJINcJo1pXMiEfJHrHwxFt+4H961cy4z8KSxV74z4bwGrkDBri9x6ogt9XAWHInkFg3xE2FGWk",
	"hfV6xwujTscPXs16fcWeS2vmH7IBf6TMScCeXWFOfIM9YQMhKfjjJn9kSmMT6zgAL92Ad4QKhvwDNhD9",
	"sB4gq0M2hIAA3W+y52zAN0U0hIFmonSep2AfVMKKuZzHTjNyYKaXCG37oIlO4HdIQG25Ta3i28Gi13JI",
	"Lh7WFkzNfjiy5ZmGbU3SWEGCJQteDNsTlb0UtvHVyCGiPbWplPCoFy76TeyI9V9Og1+63d8Q0sY9mZl5",
	"K2luJfPzV26TJhXD6qQvBv0v5IbBt9hArJzY4iTU5dsoMdXvJDwesh2xN7Nd1uOf8i3EN1FhEMR2kP3W",
	"smEaxBPx5obhRqFju//sB451keBWJIT2/IC2F10S2E0smrbWOiKSRq676LwdBeLZHRzgZtsWs46CO2Qt",
	"M8cYH2jmeNGWIStvJzYlbv6PYy07LKIcGgcBXisuDnSrXQSbrhXlafp+YNkephPN4nzasmsmsPCk6M80",
	"2jh8a3XVbtrYuWa7hOIVaZqq4YrvOwR7qXukw9xpR7exZ+k6lRjlmPZtGh2/o9Q84r6zVYGYvMhxpHgS",
	"7IyiJrEELfXyMUcOo1aLhJRYl7DVxiuTelCtci8mO9IJNhBqu+Rd3yNLIypeDG1cuXBUclTYEUD1ZiZf",
	"yJhWbqCi7EU1jDGPcXb9QnxN+EfBvUwjzTBED2NMYZxiYOBcH9op+N6q3dI5JwTbX5IgtH0PHmHLssUi",
	"YudKrmnRJEd219+K2Mg32UDAgj02hI1Wbrc9NPN+FGDPRPDf63KE0ERtbNm0baKmLYYRkCixkHVDPjQa",
	"Z8VaiXZGo24a0IPRmFV/xX0ZjTNdzcRXCaZRQCauzRtxu64p8iwSxjrJW22tXC3P6rYF1/aW4+g+9s2q",
	"7s0Au9jCEz37qmy2HLkuDtakf8J47wROfqQ2pZ2wUal42PV/Xaa3K6qhkUEKUWBP9DndlEaVk1GwWTCm",
	"nIhjrVJIZPveMsU0gmWKYym51yFNAQqhZ9GQWPrAmIsweQMXGxKNrDxomquW6wv1+amQk+N7rWIP8+fK",
	"8/V6fYoeRpSayJPtWaebC+Su3STnA4IVLs7Py4KvRzdVi9x978xqrVnF58jsyllrrlnHC2R+tbZS1QYz",
	"6t8hngYofQNc3AagXB2KLyP2J4D5PSDwMmgZAZAeCPQvstqnEj3nE8k+4g8kTQQUo3gLsoaEnHzAP+Ef",
	"lScaaKKDeCLj9XiVtOyQBkkAzisTdzrH89kfj00cEajJKB/5HvRRaNxxMBWGlvUO2w+1zvBi4m0yoplV",
	"jla/EdYoNMArdlPDchWhlr1KcaCbdOhHQXNEQ8uRhz20uGKjC/hXkYXqs2fOau06wF4osUh4AsgkX7cp",
	"SQ1mCniiJj0yuk5nMjstaI3Ejydmtq/5VhGYy9fHjgfvaACARaYa8rxoCEGfYts5AinkUEsqg0vCUB0C",
	"pOspEBHyfIqAvdFGR8nMjVpztfaLc+++OXvpzNsL1+q/nPuX+esL71YXa6/Vz080bZhxKk92iLG6O6+0",
	"lDjfCEcn0rksCSOSPkVJqejl2E3ZKuU6ROhP6SAgjhXJp/PrNzJAJr+E/iiIDfVJDsClZYKDZlvfIFzz",
	"mrpvRhQIzUzdsPkxdNr8J/t2YF/QRmoLrxWYjSLmdH1PnsukwXxss8snS9XWCA7ykszNLWiJ7FwwwiIj",
	"keKpPnQKSLiSwvxl09TGsOI8XNuLKAmB77uEW+3AXtEayF3sRCPc0Nnj4xP4Nu5MN4FRhRXBw+8VMthn",
	"A/aU32d9dsB6IsbHMGIPAMSXbJ9/yh+yARzmQcKwy7cRfyTPBNmQ7ZTz+YBYFuOH//7hv/73wx/+CqSL",
	"0TDeTFL1IBKj/we/z3bZE0AXu2K6LfX0f56qZyKgjkQrbaQinvaxGEbzmLb0YaKgwDQNj1e6jT28KvB4",
	"2Martq1d3csEBySkMcWCHeetVaNxY6qEs+Bpdkix1yRvujlzqZfnjm8vmb6K1nKraxpXArxGggt4Tefx",
	"dCQe1Kv1+VL1XGm2mk1WLJXgF/gdsZlMcvB0xxHgww3xnXFDXqvONeZqjWr1dPVMo1qQoCSQlTEGcU1E",
	"GVIN16BpceuA+cnpxP3pfE92spwCI2VA8VYsYo1iYcakStkeruAAu7mTPANH1M+wmerjcbu/FitkZGP4",
	"AxuyA8kI8G3EduDkBB6wAWI7cGK8MF+tAf0q/jlgfThkPWQD0RLxh8CrD9mO4mnZczbkj/gm6yHxGXaX",
	"XTiEHfHwMBi76rX5Rn3++KtutaP2EZ3WG7Wzx+90Fd8OjjLPMycwz5jB18t5rjE7e/w+XRWHxna70Kid",
	"QNQw8gI7JOM1MN+oV4/b7YizgYrToeKFNMFG0pkdcdaQMfKr6hxZg6tljUjBCbzIcUzE+nxTHp9ljggR",
	"e8y32T4YtYyHwqAhmYZzih47yMbDbGXJBM7QFOhkep4y3bI1ZKV7TBbZ/THkcZoDTpZXbYvJWydEfyfM",
	"n00j6ggjtBap3nyrtWtVYbuNavXdcZZ7POo3R3i7Mc/txvS20p1ae60hR2F7mVBqe61QR4p44bUx/NCf",
	"kzPexSuXQzTTJvdO6XRCvLt24HuuOs+N40on8K2oSSWBGGLPWvHv6ckMv2M3w5xCb8SEaQm4EmJb8g/s",
	"eX7kNYkLNXK3zNTUNbvXvSX5Zb064bArVUJ+MoloOr1eTRndAtsuaUxpJCexgaO4p6LXR3h6r78QYZ2/",
	"E9tadN6waTEunS1VZ0u1qZAa8awLOrAHXVTPTQ32rk+XmpmGg9ccTBedt7EVvB7zyPrRz0wzukO81kje",
	"OVvVDTzdjqU7pqM4oOOUVC9VF6YRM0xI9KPPWQu0+6jdp9rOnrep7rPCpmubKClrM8oGj/CS+EBDc/KV",
	"d57jGcBPS52J4rJ6TUUsqkcMTppRYNO1ZTFMlvSfvClD3eKVt5avocrdWkW+FcbFe0DtiGwyw7q2Ke3I",
	"ahnbW/U1fX/GP5F9s12kSmH2oWi4r6pbLsNhE2LfCCQDYGWH7cO3EqWj13DzDvGs0uKVpbJroRm+xfr8",
	"Abz9EOCQADx9CYh25dkA658q3/TYtwL0QylyrREfLH7ABuw7fj+t4zFzCYCJZD1dzClAPQ5/yD8TkplJ",
	"6iHLf3rsgPXYUyAccsPVG4h9rb4GkZBAbAdQi/aIfyg6fsAGbJc9gQoSmGZaAiteLN/0bnrsK/aYfyym",
	"I1UnVCPU10Mz339bR+zP7N9ONW56JcS+UNlQTxYkCf09A3akiV3inMchKUO7zwUe5Nvw1fXr16+XLl0q",
	"XbhgykLusRmWaD0xxcpqUQ72bZxz8W1VKaUyLuhv8fIimslho1PytfGl3UD3iGX+DuYos7k9NFKzjWb4",
	"B5mCb+Kpfr/MHiwjtsc/4R+xAd/g9+MjqAY6j5ttUjrvezTwHXQavX4Nt0y0tFq67HukdAnTZhv97cPf",
	"otnqHJoBHWXYKnUi5dqW5ZBf4YBkBs4BcqFhKB7bh2wUZOCfxsdgsjQO9ByfdvFHydcz339bmxcdJ4VO",
	"DQNcCC1eWTJM4258HKXOoLqm4XeIhzu20TBm1SF0B9M27AuVZgqfSxIJwvMWAZwhdlH4TmBa46Id0gLc",
	"Do2Roth6tfrCivH0hUu64rw/jHVaoYEzUibdUInslaRSFvbQOLgc1XWBichtCWKBsMDHAraKPMO4JXqu",
	"xMUJiZZH60LZEMr/9lQ+dwgd7qhTz0/lsSjbgYPRBynr2eMP0AxtVYKoQrwKDtBplNTUQ8oI+2ay7cEG",
	"+Rnc8IAiaulcYvN4zu+zff5I1WX2c46dK9SXRqixETnB/J2OG8Wj4pTUlQPDpGFz+8+YjP1+30TyU0zC",
	"yieKu/1+/9SYsvn4Y2pnLr53UWGxmio1Tz5rEia9taQzquRuYEzRXhbJT9OxLMaZouXILZnurZfpinEp",
	"k877vlEVq2I3zpiLcIKuacxN432ZWnrxSv3c5Fey5do/1skzTjdASQWuZj6pUys/zjp1xZNk+3jnniIW",
	"QFzryRtU+lggvoI4ICFAueCFPyc0S/sXPHGSqcbXSaYx6/hKxk/MXrPz15nsZxC3n7AeewbXFp5lFvqk",
	"Rludm/xKcvfhx1rsUROYwAQeZcHrkn/sjkUBPycnM6rM5bif4NamtZHf5Q3iVa7uV6oWKmOU49YtKdAc",
	"u1yyxcvUoBxBp8Mv9VnXC0BlA0g9DpIbFD0BnnfiUlLxQZNumoh/IDIosdWameaaytOswuX8pMLjrLix",
	"bnT8ULfJS1hFXGw7JoIO91kfkhKAboP47tZQ4KwyyubfBZFHat4Q20FvkrVmG9siQYSu5E3dXdYTqFQ0",
	"GMmR9lgfLaoSE1jdBnoN0nh0M6pWZ5tQAgd/Eh2kkxVwJJD1cGnZS1wW9EIsSFNs181zITSISLdgw7UX",
	"LEFcNqkz5b8UyhnVfY+nincYnjBw/ChH+Brukg5iYB5fTgJ5lIckt4t016pEOptevcoYfWznOauvuKTS",
	"iUIgNDsR1ZJJfXbAtxsoZtvXFQ3YNRGxrezHHPNevuldicK2Sm/2WI89gfuyzzJplYJKQ76V8CH7/FGS",
	"eYsUhn8iJiPh1F68N0Aew+8LdwcYd6AYpnG7hM4NlgmVJiKkfElekDtXmcr+57Q1uAlYlDzaifFMbfIr",
	"uSuEJ7NlRVeqHDFDVN64JeJ+auuLVy6Hpcw1Qbn9CWT+XCWPA1U0vCWNcKw1y4S8lBRg6MH671I8pchF",
	"scPKsuOHyQ8kSMCE2Bfs9+wL5GCKTiPH99BplJ6ziWT7c7jt91zRA4doNfDdcpn6MvMGw34sa5n5R6yP",
	"5uuI7cIKPivf9OTpwD/iiPoN/fXBvubyIOtnT4z7kp00kYKDD5N3JKFRvunN1esoU2koRYs7UDLERR0m",
	"Eo6qEwXucvbYY2AdPlQZDvSvy1SypR+TOIOx9/Dy9CMC5vSRWLU4/LLDrCrU1c0kcsLvDjiYVhzfq2SW",
	"bdyl/Ph3HI77uw1HXc9/Udfxj7oa/8KuwpujSwN8bq7M5llC+ZqIDYvrIdCXpMS3IMWN9T9G5/lbWhq9",
	"T6xT1ytGuOGUvyBxnCKzccNBXdTUg9WqUw9WZBFFxDuAHeVhQh4Khx654jZaAKWTOikSOCFvu2SdXEgo",
	"S5hKyKSAYSoh40qTcSuVlEFMGbsLBXLdl5q16oqJ9L+AUAgKr4rfmKvXpwEQaWH7/wfzp9HPCJGvIOnu",
	"SPwGPLA1juVX6LeynhzcdscCjbnqXD7SqnzikG/zBwrRAKwV6d13EpD0+cf8s/j3BGa0eSNM6bm6HqVO",
	"qBD7CztgB0hG6xL7Uiblp8bE5rggpRCXNT9ulD2hnmKDk+fvadCZz//+y1y1qqucn5aWT35x6CfGNcUK",
	"HeOp6Ynx3wUHGR8n50VXHMcXcGA0erbdR6cR2+X3c/yKLGC+1ZXpQHA3trIocDLXUnHHLidXU+/WYGnT",
	"Fo1KBa7Gtf2QNhaqC1VocisZZD391ShJVpnrGThnwwXe5Ily5cwTKWLmgUwojO6t7v8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
