//go:build go1.22

// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CalculationMethodId.
const (
	Egypt             CalculationMethodId = "egypt"
	Karachi           CalculationMethodId = "karachi"
	MuslimWorldLeague CalculationMethodId = "muslimWorldLeague"
	NorthAmerica      CalculationMethodId = "northAmerica"
	Turkey            CalculationMethodId = "turkey"
	UmmAlQura         CalculationMethodId = "ummAlQura"
)

// Valid indicates whether the value is a known member of the CalculationMethodId enum.
func (e CalculationMethodId) Valid() bool {
	switch e {
	case Egypt:
		return true
	case Karachi:
		return true
	case MuslimWorldLeague:
		return true
	case NorthAmerica:
		return true
	case Turkey:
		return true
	case UmmAlQura:
		return true
	default:
		return false
	}
}

// Defines values for ConfirmationStatus.
const (
	Confirmed ConfirmationStatus = "confirmed"
	Expected  ConfirmationStatus = "expected"
)

// Valid indicates whether the value is a known member of the ConfirmationStatus enum.
func (e ConfirmationStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Expected:
		return true
	default:
		return false
	}
}

// Defines values for DeviceRegistrationPlatform.
const (
	Ios DeviceRegistrationPlatform = "ios"
)

// Valid indicates whether the value is a known member of the DeviceRegistrationPlatform enum.
func (e DeviceRegistrationPlatform) Valid() bool {
	switch e {
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeInternal        ErrorCode = "internal"
	ErrorCodeInvalidArgument ErrorCode = "invalid_argument"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRateLimited     ErrorCode = "rate_limited"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
	ErrorCodeUnsupported     ErrorCode = "unsupported"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidArgument:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for IshaRuleType.
const (
	Angle               IshaRuleType = "angle"
	MinutesAfterMaghrib IshaRuleType = "minutesAfterMaghrib"
)

// Valid indicates whether the value is a known member of the IshaRuleType enum.
func (e IshaRuleType) Valid() bool {
	switch e {
	case Angle:
		return true
	case MinutesAfterMaghrib:
		return true
	default:
		return false
	}
}

// Defines values for Madhab.
const (
	Hanafi Madhab = "hanafi"
	Shafii Madhab = "shafii"
)

// Valid indicates whether the value is a known member of the Madhab enum.
func (e Madhab) Valid() bool {
	switch e {
	case Hanafi:
		return true
	case Shafii:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSource.
const (
	PrayerSourceCalculated PrayerSource = "calculated"
	PrayerSourceOfficial   PrayerSource = "official"
)

// Valid indicates whether the value is a known member of the PrayerSource enum.
func (e PrayerSource) Valid() bool {
	switch e {
	case PrayerSourceCalculated:
		return true
	case PrayerSourceOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSourceParam.
const (
	PrayerSourceParamAuto       PrayerSourceParam = "auto"
	PrayerSourceParamCalculated PrayerSourceParam = "calculated"
	PrayerSourceParamOfficial   PrayerSourceParam = "official"
)

// Valid indicates whether the value is a known member of the PrayerSourceParam enum.
func (e PrayerSourceParam) Valid() bool {
	switch e {
	case PrayerSourceParamAuto:
		return true
	case PrayerSourceParamCalculated:
		return true
	case PrayerSourceParamOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PushSettingsEnvironment.
const (
	Production PushSettingsEnvironment = "production"
	Sandbox    PushSettingsEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the PushSettingsEnvironment enum.
func (e PushSettingsEnvironment) Valid() bool {
	switch e {
	case Production:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// CalculationMethod defines model for CalculationMethod.
type CalculationMethod struct {
	// FajrAngle Example: 18
	FajrAngle float64 `json:"fajrAngle"`

	// Id Идентификаторы строго совпадают с CalculationMethod в iOS
	Id   CalculationMethodId `json:"id"`
	Isha IshaRule            `json:"isha"`

	// Title Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Title LocalizedString `json:"title"`
}

// CalculationMethodId Идентификаторы строго совпадают с CalculationMethod в iOS
type CalculationMethodId string

// CalculationMethodList defines model for CalculationMethodList.
type CalculationMethodList struct {
	Items []CalculationMethod `json:"items"`
}

// City defines model for City.
type City struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country              string `json:"country"`
	HasOfficialTimetable bool   `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// CityList defines model for CityList.
type CityList struct {
	Items      []City  `json:"items"`
	NextCursor *string `json:"nextCursor"`
}

// Config defines model for Config.
type Config struct {
	// ContentVersions Версии контента (quran, quranEditions, hadith, cities)
	//
	// Example: {"cities":7,"hadith":2,"quran":3,"quranEditions":5}
	ContentVersions map[string]int `json:"contentVersions"`
	Features        Features       `json:"features"`

	// LatestVersion Example: 1.0.3
	LatestVersion string `json:"latestVersion"`

	// MinSupportedVersion Example: 1.0.0
	MinSupportedVersion string          `json:"minSupportedVersion"`
	Ramadan             *RamadanSummary `json:"ramadan,omitempty"`

	// SupportUrl Example: https://namoz.tj/support
	SupportUrl string `json:"supportUrl"`
}

// ConfirmationStatus defines model for ConfirmationStatus.
type ConfirmationStatus string

// Coordinate defines model for Coordinate.
type Coordinate struct {
	// Latitude Example: 40.2826
	Latitude float64 `json:"latitude"`

	// Longitude Example: 69.6222
	Longitude float64 `json:"longitude"`
}

// DailyReminder defines model for DailyReminder.
type DailyReminder struct {
	Day int `json:"day"`

	// Text Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Text LocalizedString `json:"text"`
}

// DeviceCreated defines model for DeviceCreated.
type DeviceCreated struct {
	// DeviceId Example: dev_5f1c0a9e3b7d4c2a8e6f1b0d
	DeviceId string `json:"deviceId"`

	// Token Секрет устройства. Показывается один раз, на сервере хранится только хэш.
	Token string `json:"token"`
}

// DeviceRegistration defines model for DeviceRegistration.
type DeviceRegistration struct {
	// AppVersion Example: 1.0.0
	AppVersion string `json:"appVersion"`

	// Country Example: TJ
	Country *string `json:"country,omitempty"`

	// Locale Example: ru_TJ
	Locale   *string                    `json:"locale,omitempty"`
	Platform DeviceRegistrationPlatform `json:"platform"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId *string `json:"timeZoneId,omitempty"`
}

// DeviceRegistrationPlatform defines model for DeviceRegistration.Platform.
type DeviceRegistrationPlatform string

// Dua defines model for Dua.
type Dua struct {
	Arabic string `json:"arabic"`

	// Id Example: iftar
	Id string `json:"id"`

	// Source Example: Sunan Abi Dawud 2357
	Source *string `json:"source,omitempty"`

	// Translations Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Translations    LocalizedString `json:"translations"`
	Transliteration *string         `json:"transliteration,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    ErrorCode               `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Example: City not found
	Message string `json:"message"`

	// RequestId Example: 01J9ZK3M5Q8T2V4X6Y8Z0A1B2C
	RequestId string `json:"requestId"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Features defines model for Features.
type Features struct {
	OfficialTimetables bool `json:"officialTimetables"`
	QuranSearch        bool `json:"quranSearch"`
	Sync               bool `json:"sync"`
}

// HijriDate defines model for HijriDate.
type HijriDate struct {
	// Day Example: 18
	Day int `json:"day"`

	// Month Example: 4
	Month int `json:"month"`

	// MonthName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	MonthName *LocalizedString `json:"monthName,omitempty"`

	// Year Example: 1448
	Year int `json:"year"`
}

// HijriMonthList defines model for HijriMonthList.
type HijriMonthList struct {
	Items []HijriMonthStart `json:"items"`
}

// HijriMonthStart defines model for HijriMonthStart.
type HijriMonthStart struct {
	// Month Example: 9
	Month int `json:"month"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// IshaRule defines model for IshaRule.
type IshaRule struct {
	Type IshaRuleType `json:"type"`

	// Value Example: 17
	Value float64 `json:"value"`
}

// IshaRuleType defines model for IshaRule.Type.
type IshaRuleType string

// LocalizedString Локализуемая строка. Ключи — коды языков.
//
// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
type LocalizedString struct {
	Ar *string `json:"ar,omitempty"`
	En *string `json:"en,omitempty"`
	Ru *string `json:"ru,omitempty"`
	Tg *string `json:"tg,omitempty"`
}

// Madhab defines model for Madhab.
type Madhab string

// NearestCity defines model for NearestCity.
type NearestCity struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country string `json:"country"`

	// DistanceKm Example: 2.4
	DistanceKm           float64 `json:"distanceKm"`
	HasOfficialTimetable bool    `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// PrayerDay defines model for PrayerDay.
type PrayerDay struct {
	// Date Example: 2026-09-30
	Date  openapi_types.Date `json:"date"`
	Hijri HijriDate          `json:"hijri"`

	// Imsak Example: 2026-09-30T04:41:00+05:00
	Imsak *time.Time `json:"imsak,omitempty"`

	// Times Моменты времени в ISO 8601 со смещением часового пояса города
	Times PrayerTimes `json:"times"`
}

// PrayerSource defines model for PrayerSource.
type PrayerSource string

// PrayerSourceParam defines model for PrayerSourceParam.
type PrayerSourceParam string

// PrayerTimes Моменты времени в ISO 8601 со смещением часового пояса города
type PrayerTimes struct {
	// Asr Example: 2026-09-30T16:26:00+05:00
	Asr time.Time `json:"asr"`

	// Dhuhr Example: 2026-09-30T12:17:00+05:00
	Dhuhr time.Time `json:"dhuhr"`

	// Fajr Example: 2026-09-30T04:51:00+05:00
	Fajr time.Time `json:"fajr"`

	// Isha Example: 2026-09-30T19:33:00+05:00
	Isha time.Time `json:"isha"`

	// Maghrib Example: 2026-09-30T18:11:00+05:00
	Maghrib time.Time `json:"maghrib"`

	// Sunrise Example: 2026-09-30T06:20:00+05:00
	Sunrise time.Time `json:"sunrise"`
}

// PrayerTimesResponse defines model for PrayerTimesResponse.
type PrayerTimesResponse struct {
	// CityId null, если запрос был по координатам
	//
	// Example: dushanbe
	CityId *string     `json:"cityId,omitempty"`
	Days   []PrayerDay `json:"days"`
	Madhab Madhab      `json:"madhab"`

	// Method Идентификаторы строго совпадают с CalculationMethod в iOS
	Method CalculationMethodId `json:"method"`
	Source PrayerSource        `json:"source"`

	// SourceName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	SourceName *LocalizedString `json:"sourceName,omitempty"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`

	// UpdatedAt Example: 2026-09-01T00:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PushSettings defines model for PushSettings.
type PushSettings struct {
	// ApnsToken Токен APNs (hex)
	ApnsToken   string                  `json:"apnsToken"`
	Environment PushSettingsEnvironment `json:"environment"`

	// Topics Example: ["ramadan-TJ","eid-TJ","announcements"]
	Topics []string `json:"topics"`
}

// PushSettingsEnvironment defines model for PushSettings.Environment.
type PushSettingsEnvironment string

// Ramadan defines model for Ramadan.
type Ramadan struct {
	ConfirmedAt *time.Time `json:"confirmedAt,omitempty"`

	// Country Example: TJ
	Country        string          `json:"country"`
	DailyReminders []DailyReminder `json:"dailyReminders"`
	Duas           []Dua           `json:"duas"`

	// EidAlFitr Example: 2027-03-10
	EidAlFitr openapi_types.Date `json:"eidAlFitr"`

	// EndDate Example: 2027-03-09
	EndDate openapi_types.Date `json:"endDate"`

	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// LaylatAlQadrExpected Example: 2027-03-05
	LaylatAlQadrExpected *openapi_types.Date `json:"laylatAlQadrExpected,omitempty"`

	// Length Example: 30
	Length int `json:"length"`

	// Source Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Source *LocalizedString `json:"source,omitempty"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// RamadanSummary defines model for RamadanSummary.
type RamadanSummary struct {
	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// AcceptLanguage Example: ru
type AcceptLanguage = string

// CityIdPath Example: dushanbe
type CityIdPath = string

// CountryQuery Example: TJ
type CountryQuery = string

// CountryRequired Example: TJ
type CountryRequired = string

// Cursor defines model for Cursor.
type Cursor = string

// LatQuery defines model for LatQuery.
type LatQuery = float64

// Limit defines model for Limit.
type Limit = int

// LonQuery defines model for LonQuery.
type LonQuery = float64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unsupported defines model for Unsupported.
type Unsupported = Error

// ListCitiesParams defines parameters for ListCities.
type ListCitiesParams struct {
	// Query Строка поиска («Худж», «Хуҷанд», «Khujand»)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Country Код страны ISO 3166-1 alpha-2
	Country *CountryQuery `form:"country,omitempty" json:"country,omitempty"`
	Limit   *Limit        `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор из nextCursor предыдущего ответа
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetNearestCityParams defines parameters for GetNearestCity.
type GetNearestCityParams struct {
	Lat LatQuery `form:"lat" json:"lat"`
	Lon LonQuery `form:"lon" json:"lon"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetCityParams defines parameters for GetCity.
type GetCityParams struct {
	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetHijriMonthsParams defines parameters for GetHijriMonths.
type GetHijriMonthsParams struct {
	// Country Код страны ISO 3166-1 alpha-2
	Country CountryRequired `form:"country" json:"country"`

	// Year Год хиджры
	Year int `form:"year" json:"year"`
}

// GetPrayerTimesParams defines parameters for GetPrayerTimes.
type GetPrayerTimesParams struct {
	// CityId Идентификатор города. Обязателен, если не переданы lat/lon/timeZoneId.
	CityId *string  `form:"cityId,omitempty" json:"cityId,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Lon    *float64 `form:"lon,omitempty" json:"lon,omitempty"`

	// TimeZoneId IANA часовой пояс, обязателен вместе с lat/lon
	TimeZoneId *string            `form:"timeZoneId,omitempty" json:"timeZoneId,omitempty"`
	From       openapi_types.Date `form:"from" json:"from"`
	To         openapi_types.Date `form:"to" json:"to"`

	// Method По умолчанию — suggestedMethod города
	Method *CalculationMethodId `form:"method,omitempty" json:"method,omitempty"`

	// Madhab По умолчанию — suggestedMadhab города
	Madhab *Madhab            `form:"madhab,omitempty" json:"madhab,omitempty"`
	Source *PrayerSourceParam `form:"source,omitempty" json:"source,omitempty"`
}

// GetRamadanParams defines parameters for GetRamadan.
type GetRamadanParams struct {
	// Country Код страны ISO 3166-1 alpha-2
	Country CountryRequired `form:"country" json:"country"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistration

// SetDevicePushJSONRequestBody defines body for SetDevicePush for application/json ContentType.
type SetDevicePushJSONRequestBody = PushSettings

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(w http.ResponseWriter, r *http.Request)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(w http.ResponseWriter, r *http.Request, params ListCitiesParams)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(w http.ResponseWriter, r *http.Request, params GetNearestCityParams)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(w http.ResponseWriter, r *http.Request, cityId CityIdPath, params GetCityParams)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// DeleteDevice Удалить устройство и все его данные
	// (DELETE /devices/me)
	DeleteDevice(w http.ResponseWriter, r *http.Request)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(w http.ResponseWriter, r *http.Request)
	// GetHijriMonths Начала месяцев хиджры по стране (подтверждённые/ожидаемые)
	// (GET /hijri/months)
	GetHijriMonths(w http.ResponseWriter, r *http.Request, params GetHijriMonthsParams)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(w http.ResponseWriter, r *http.Request, params GetPrayerTimesParams)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(w http.ResponseWriter, r *http.Request, hijriYear int, params GetRamadanParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCalculationMethods operation middleware
func (siw *ServerInterfaceWrapper) ListCalculationMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalculationMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCities operation middleware
func (siw *ServerInterfaceWrapper) ListCities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCitiesParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNearestCity operation middleware
func (siw *ServerInterfaceWrapper) GetNearestCity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearestCityParams

	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNearestCity(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCity operation middleware
func (siw *ServerInterfaceWrapper) GetCity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cityId" -------------
	var cityId CityIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "cityId", r.PathValue("cityId"), &cityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cityId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCityParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCity(w, r, cityId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDevicePush operation middleware
func (siw *ServerInterfaceWrapper) SetDevicePush(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDevicePush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHijriMonths operation middleware
func (siw *ServerInterfaceWrapper) GetHijriMonths(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHijriMonthsParams

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Required query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "year", r.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHijriMonths(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrayerTimes operation middleware
func (siw *ServerInterfaceWrapper) GetPrayerTimes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPrayerTimesParams

	// ------------- Optional query parameter "cityId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cityId", r.URL.Query(), &params.CityId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cityId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cityId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "timeZoneId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeZoneId", r.URL.Query(), &params.TimeZoneId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "timeZoneId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeZoneId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", r.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "madhab" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "madhab", r.URL.Query(), &params.Madhab, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "madhab"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "madhab", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrayerTimes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRamadan operation middleware
func (siw *ServerInterfaceWrapper) GetRamadan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hijriYear" -------------
	var hijriYear int

	err = runtime.BindStyledParameterWithOptions("simple", "hijriYear", r.PathValue("hijriYear"), &hijriYear, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hijriYear", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRamadanParams

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRamadan(w, r, hijriYear, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/config", wrapper.GetConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities", wrapper.ListCities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities/nearest", wrapper.GetNearestCity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities/{cityId}", wrapper.GetCity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/calculation-methods", wrapper.ListCalculationMethods)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/prayer-times", wrapper.GetPrayerTimes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ramadan/{hijriYear}", wrapper.GetRamadan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hijri/months", wrapper.GetHijriMonths)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/devices/me", wrapper.DeleteDevice)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/devices/me/push", wrapper.SetDevicePush)

	return m
}

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedResponseHeaders struct {
	RetryAfter *int
}
type RateLimitedJSONResponse struct {
	Body Error

	Headers RateLimitedResponseHeaders
}

type UnauthorizedJSONResponse Error

type UnsupportedJSONResponse Error

type ListCalculationMethodsRequestObject struct {
}

type ListCalculationMethodsResponseObject interface {
	VisitListCalculationMethodsResponse(w http.ResponseWriter) error
}

type ListCalculationMethods200JSONResponse CalculationMethodList

func (response ListCalculationMethods200JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCalculationMethods500JSONResponse struct{ InternalJSONResponse }

func (response ListCalculationMethods500JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCitiesRequestObject struct {
	Params ListCitiesParams
}

type ListCitiesResponseObject interface {
	VisitListCitiesResponse(w http.ResponseWriter) error
}

type ListCities200JSONResponse CityList

func (response ListCities200JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities400JSONResponse struct{ BadRequestJSONResponse }

func (response ListCities400JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListCities429JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities500JSONResponse struct{ InternalJSONResponse }

func (response ListCities500JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCityRequestObject struct {
	Params GetNearestCityParams
}

type GetNearestCityResponseObject interface {
	VisitGetNearestCityResponse(w http.ResponseWriter) error
}

type GetNearestCity200JSONResponse NearestCity

func (response GetNearestCity200JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity400JSONResponse struct{ BadRequestJSONResponse }

func (response GetNearestCity400JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetNearestCity404JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity500JSONResponse struct{ InternalJSONResponse }

func (response GetNearestCity500JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCityRequestObject struct {
	CityId CityIdPath `json:"cityId"`
	Params GetCityParams
}

type GetCityResponseObject interface {
	VisitGetCityResponse(w http.ResponseWriter) error
}

type GetCity200JSONResponse City

func (response GetCity200JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCity404JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity500JSONResponse struct{ InternalJSONResponse }

func (response GetCity500JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfig500JSONResponse struct{ InternalJSONResponse }

func (response GetConfig500JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice201JSONResponse DeviceCreated

func (response RegisterDevice201JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice500JSONResponse struct{ InternalJSONResponse }

func (response RegisterDevice500JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceRequestObject struct {
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteDevice401JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDevice500JSONResponse struct{ InternalJSONResponse }

func (response DeleteDevice500JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePushRequestObject struct {
	Body *SetDevicePushJSONRequestBody
}

type SetDevicePushResponseObject interface {
	VisitSetDevicePushResponse(w http.ResponseWriter) error
}

type SetDevicePush204Response struct {
}

func (response SetDevicePush204Response) VisitSetDevicePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetDevicePush400JSONResponse struct{ BadRequestJSONResponse }

func (response SetDevicePush400JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SetDevicePush401JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush500JSONResponse struct{ InternalJSONResponse }

func (response SetDevicePush500JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonthsRequestObject struct {
	Params GetHijriMonthsParams
}

type GetHijriMonthsResponseObject interface {
	VisitGetHijriMonthsResponse(w http.ResponseWriter) error
}

type GetHijriMonths200JSONResponse HijriMonthList

func (response GetHijriMonths200JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonths400JSONResponse struct{ BadRequestJSONResponse }

func (response GetHijriMonths400JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonths500JSONResponse struct{ InternalJSONResponse }

func (response GetHijriMonths500JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimesRequestObject struct {
	Params GetPrayerTimesParams
}

type GetPrayerTimesResponseObject interface {
	VisitGetPrayerTimesResponse(w http.ResponseWriter) error
}

type GetPrayerTimes200JSONResponse PrayerTimesResponse

func (response GetPrayerTimes200JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPrayerTimes400JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPrayerTimes404JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes422JSONResponse struct{ UnsupportedJSONResponse }

func (response GetPrayerTimes422JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetPrayerTimes429JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes500JSONResponse struct{ InternalJSONResponse }

func (response GetPrayerTimes500JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadanRequestObject struct {
	HijriYear int `json:"hijriYear"`
	Params    GetRamadanParams
}

type GetRamadanResponseObject interface {
	VisitGetRamadanResponse(w http.ResponseWriter) error
}

type GetRamadan200JSONResponse Ramadan

func (response GetRamadan200JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRamadan400JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRamadan404JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan500JSONResponse struct{ InternalJSONResponse }

func (response GetRamadan500JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(ctx context.Context, request ListCalculationMethodsRequestObject) (ListCalculationMethodsResponseObject, error)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(ctx context.Context, request ListCitiesRequestObject) (ListCitiesResponseObject, error)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(ctx context.Context, request GetNearestCityRequestObject) (GetNearestCityResponseObject, error)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(ctx context.Context, request GetCityRequestObject) (GetCityResponseObject, error)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// DeleteDevice Удалить устройство и все его данные
	// (DELETE /devices/me)
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(ctx context.Context, request SetDevicePushRequestObject) (SetDevicePushResponseObject, error)
	// GetHijriMonths Начала месяцев хиджры по стране (подтверждённые/ожидаемые)
	// (GET /hijri/months)
	GetHijriMonths(ctx context.Context, request GetHijriMonthsRequestObject) (GetHijriMonthsResponseObject, error)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(ctx context.Context, request GetPrayerTimesRequestObject) (GetPrayerTimesResponseObject, error)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(ctx context.Context, request GetRamadanRequestObject) (GetRamadanResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCalculationMethods operation middleware
func (sh *strictHandler) ListCalculationMethods(w http.ResponseWriter, r *http.Request) {
	var request ListCalculationMethodsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalculationMethods(ctx, request.(ListCalculationMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalculationMethods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCalculationMethodsResponseObject); ok {
		if err := validResponse.VisitListCalculationMethodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCities operation middleware
func (sh *strictHandler) ListCities(w http.ResponseWriter, r *http.Request, params ListCitiesParams) {
	var request ListCitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCities(ctx, request.(ListCitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCitiesResponseObject); ok {
		if err := validResponse.VisitListCitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNearestCity operation middleware
func (sh *strictHandler) GetNearestCity(w http.ResponseWriter, r *http.Request, params GetNearestCityParams) {
	var request GetNearestCityRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNearestCity(ctx, request.(GetNearestCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNearestCity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNearestCityResponseObject); ok {
		if err := validResponse.VisitGetNearestCityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCity operation middleware
func (sh *strictHandler) GetCity(w http.ResponseWriter, r *http.Request, cityId CityIdPath, params GetCityParams) {
	var request GetCityRequestObject

	request.CityId = cityId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCity(ctx, request.(GetCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCityResponseObject); ok {
		if err := validResponse.VisitGetCityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request) {
	var request DeleteDeviceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetDevicePush operation middleware
func (sh *strictHandler) SetDevicePush(w http.ResponseWriter, r *http.Request) {
	var request SetDevicePushRequestObject

	var body SetDevicePushJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetDevicePush(ctx, request.(SetDevicePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetDevicePush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetDevicePushResponseObject); ok {
		if err := validResponse.VisitSetDevicePushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHijriMonths operation middleware
func (sh *strictHandler) GetHijriMonths(w http.ResponseWriter, r *http.Request, params GetHijriMonthsParams) {
	var request GetHijriMonthsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHijriMonths(ctx, request.(GetHijriMonthsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHijriMonths")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHijriMonthsResponseObject); ok {
		if err := validResponse.VisitGetHijriMonthsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPrayerTimes operation middleware
func (sh *strictHandler) GetPrayerTimes(w http.ResponseWriter, r *http.Request, params GetPrayerTimesParams) {
	var request GetPrayerTimesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPrayerTimes(ctx, request.(GetPrayerTimesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPrayerTimes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPrayerTimesResponseObject); ok {
		if err := validResponse.VisitGetPrayerTimesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRamadan operation middleware
func (sh *strictHandler) GetRamadan(w http.ResponseWriter, r *http.Request, hijriYear int, params GetRamadanParams) {
	var request GetRamadanRequestObject

	request.HijriYear = hijriYear
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRamadan(ctx, request.(GetRamadanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRamadan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRamadanResponseObject); ok {
		if err := validResponse.VisitGetRamadanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FxbbxzHlf4rhd48kFDPlRRFDbAPtGRnGUuyLMrZlSWtUZwuzrTUl0l3tSKGIEBSluWAsQUlAdZwEseO",
	"d+GHXWxGNEca8TIC/Auq9sn7ml+yqFPVt+kazpC6RPsicWaqq06dOpfvXKrXjKbvdnyPeDQ0GmtGm2CL",
	"BPDnFUKD1YUVSgLxySJhM7A71PY9o2Gw71iPb7Aee4r4JttjA7bPfyP+Fx97bI/fY4dsF7EDNmBP2CEb",
	"IPacDdgO32IDvsH6fIv/BrGnrMue8w024JuGaYTNNnGxWIuudojRMGyPkhYJjPX1ddPo4AC7hCraFppN",
	"0qEXsNeKcIto6Psre8q32R76YLHEt4CiTbE220FTtGWiIDIR8UyEg+kyYv8u6GeP+WdsD/1t4/eIeGXD",
	"NGwxkeSHYRoedgVNcuFSsnKWbHIXux1HjAoiw4x3EdLA9lqG2MM5m64uWpcxbYvhMH9HfEhmb8IAwzQC",
	"8ovIDohlNGgQEf0iVhS2sbdM9Ev5kUeD1fcjEqxq2PMlG7BdJHjCN1iXHfJttLj0Hpqpzc2Vagg7nTYu",
	"1WMe/AImSYmUU4/Y+tWfGeKwKCWBePZfry+UPry5Vl//yVFkXkm2+4oonYSfx6Q8CkJfpxl/Yj0p1Oyp",
	"oJg/EDSzZ0goBd/gm0IBEOuzp8gjd6mcBsETPbbLt9kuv8d/zXrse6E0A77FdliPb7HuqD1KOjTqkyH2",
	"AqaJJOgmcTA9kkkrfuBiKmTOj5YdIXEuvmu7kWs0zlZNw7U9+aEkPqnlvchdBuU1jQu2a9ORa8OP2dUs",
	"soIjhxqN09XMQvVqdqWaWbQSpnHB947ep++ddJ+1+dxG4ePwTtfF3GHH90ICVuotbAnJJiFsvul7lHjw",
	"J+50HLuJhchUboVCbtYyVPwkICtGw/iHSmqaK/LXsPJ2EPhqKY3c7YBVVvL2nHVBZQ6E/PANNGV7d7Bj",
	"Wx/hoBW5xKPTxrppLHpC3rHzGij8in/K+uwx22NdcBN8QxHcFbRJMoCmSz59x4886zXQ9DXr8U2pmIgd",
	"sp74p8uesV3WY4doyvPpRyuCFKDrCqYEZJm8DtL+DCZhh2/zT4EYts/67ED4zpznlE4twJR85Ejapg2z",
	"4MdLiSPXEaNGVzIuHyj6wMMRbfuB/avXsuM/CUkVtnGf9eE0cgIN/nsPWMHvKYcwYM/Ase8IGYoy1MJ5",
	"feCFUafjB6/nvL5iz6U0809Ynz9U4iRgz64QJ77BnrC+oBT0cZM/NKWwiXPsg5ZuwDOCBQP+MeuLeVgX",
	"kNUhG4BDgOk32XPW55vCG8JCU1G6z2mwg4pYsZdz2GlGDuz0IqFtHzjRCfwOCagtzdQKvhUseC2H5Pxh",
	"bd7U2MMhk2catjWOYwUKFi14MGyPZfZi2MZXIoeI8dSmksKjHrjgN7Ejzn8pdX6pub8uqI1nMjP7VtTc",
	"TPbnL98iTSqW1VFfdPpfSIPBt1hfnJwwcRLq8m2UiOr3Eh4P2I6wzWyXdfnnfAvxTVRYBLEdZL+3ZJgG",
	"8YS/uW64UejY7j/7gWNdILgVCaI9P6DtBZcEdhOLoa3VjvCkkesuOO9HgfjuNg5ws22LXUfBbbKa2WOM",
	"DzR7vGBLl5WXE5sSN//HsY4dDlEujYMArxYPB6bVHoJNV4v0NH0/sGwP07FicS4duW4msPCk6M802jh8",
	"b2XFbtrYuWq7hOJlKZpq4LLvOwR7qXqky9xuR7ewZ+kmlRjlmPJtGh2/o9g8pL4zVYGYvMhxJHkS7Ayj",
	"JnEELfXwMVcOo1aLhJRYF7HVxsvjZlCjcg8mFukEBoTaLvnQ98jiEIsXQhtXzh8VHBUsArDezMQLGdHK",
	"LVSkvciGEeIxSq5fiq4J/Siol2mkEYaYYYQojGIMLJybQ7sF31uxWzrlBGf7cxKEtu/BV9iybHGI2Lmc",
	"G1oUySHr+lvhG/km6wtYsMcGYGilue2iqV9EAfZMBP+9LVcITdTGlk3bJmraYhkBiRIJWTPkl0bjjDgr",
	"Mc5o1E0DZjAaM+qveC6jcXpds/EVgmkUkLFn8048bt0UcRYJY57kpbZWrpZndGbBtb2l2LuPfLKqezLA",
	"LrbwWM2+IoctRa6Lg1Wpn7DeB4GTX6lNaSdsVCoedv1flemtihpoZJBCFNhjdU63pWHmZBhsFoQpR+JI",
	"qRQU2b63RDGN4JhiX0rudkhTgEKYWQwklt4x5jxMXsCFQaKRlQdNs9Vyfb4+NxFycnyvVZxh7mx5rl6v",
	"TzDDEFMTerIz63hzHtvO6hXi2p4lI4L8viwMnjEJfGfGhN2mQcld+qLATKyqZtLSTO7YTXIuIFhh+SGa",
	"4edhR2CROx+dXqk1q/gsmVk+Y80263iezK3UlqtaB0z928TTgLtvIH+4AchcF3mUEfszhCZdSDpmED4C",
	"8N8XEYuIxJ9KxJ8PfnuI35epLUiLiqcg0kkSqvf5Z/zT8lilSngQb2Q0H6+Qlh3SIAENeWbiTud4dubF",
	"8ZQjpIMM51A/gjkKgzsOpkI5shpt+6FWgV8ORkhWNLPM0fI3whqGBnjZbmoyc0V4aK9QHOg2HfpR0Bzi",
	"0FLkYQ8tLNvoPP5lZKH6zOkzWrkOsBdK/BSeAObJx21KUoGZAFKpTQ+truOZjKgLXCPx12Oj8bd8qxhM",
	"yMdHrgfPaECLRSZa8pwYCECFYts5At3kkFZKg0vCUBUu0vMUKA55PkWQcdJ6dJlNHJbmau1nZz98d+bi",
	"6ffnr9Z/Pvsvc9fmP6wu1N6qnxsr2rDjlJ7sEiN5d05xKVG+obyiCEGziSMRqKo0mvK4jt2Uo9L8jIAr",
	"aQoLkt0qManT63cy4Ct/hP4w8A71gRlAvCWCg2ZbPyBc9Zq6X4YYCMNM3bL5NXTc/Cf7VmCf16IL5YVz",
	"2Zii53V9T9aSUgAyctilk4WXqwQHeUpmZ+e1yfeiO5fkqTlGMuCiGPUyoqB0tiWKA/oC+YbhmQqEFRl/",
	"NlsrqI+DTKGYNj75VJHr1fqZUrVeqs5nIbWlwtCCT0iA7dG5jwIULuBxdU4pVcnkOu4kWbkCW+TQ1DJg",
	"lV1zbS+iJITM8kXcagf2slat72AnGspCnjk+EoZf48l0GxgW8yLk+4PCc/usz57ye6zHDlhXILMY/O0B",
	"7PuS7fPP+QPWh7IxhKa7fBvxh7L6zAZsp5yPPIUyGT/+94//9b+f/PhXSO8ZDePdJCkURGL1/+D32C57",
	"AphwV2y3pb79n6fqOwGDhjCGFl8QT/u1WEbzNW3pnXuBgWnCJz7pNvbwioj8wjZesW3t6V4iOCAhjZN5",
	"2HHeWzEa1ydKbRTsox1S7DXJu25OXOrl2ePLS2auorTcXDeNywFeJcF5vKqz0xodnitVz5ZmqpPocFtY",
	"mokM23mVvbTdEN8eteTV6mxjttaoVk9VTzeqBQpKAg8bI3DyWEsi2XAVhhYNPuxPbieeT6d7cpKlFM4q",
	"AYodqEAIKt83IijPznAZB9jN1YwNHFE/kzdXH487/dWYIUOG4Y9swA5k7olvI7YDNTr4gvUR24HehPm5",
	"ag0S/eKfA9aDcv4h64uRiD+ACs6A7aiKAHvOBvwh32RdJD6DddmFcv+QhofByFOvzTXqc8c/dasdtY+Y",
	"tN6onTn+pCv4VnCUeJ4+gXjGtSI9nWcbMzPHn9NVfmjktPON2glIDSMvsEMymgNzjXr1uNMOKRuwOF0q",
	"PkgTZCTd2RFVrYyQX1EdC5poSHYjFZTAixzHRKzHN2WhNlOMRuwx32b7INTSHwqBhhQIVMS67CDrD7M9",
	"TGOy06bAlJNjwdRka9Li7jHrFe6LlCnSyH08vcosJk+dELOfMOthGlFHCKG1QPXiW61drQrZbVSrH46S",
	"3OMVGXKlFTeuqLhxIUXxTp29VpCjsL1EKLW9VqhLZXnh1RFZvb8k3QQLly+FaKpN7k7reEK8O3bge67q",
	"HIj9SifwrahJZao6xJ617N/Vp6D8jt0Mcwy9HqfmS5DhIrYl/8Ce50dek7jQjXnTTEVdY73uLsof69Ux",
	"YU7KhPxmEtJ0fL2S1g4KdR2ZMJdCchIZOCpjqNH6TLZ6cv3PJ7k1NsCK8DFmi7BuDmJbC847Ng10UdxM",
	"qTYRAiSeNSoQnClVz04MIq9NFqibhoNXHUwXnPexFbwdV0L0q5+eZHWHeK2hYHimqg16J7KEukLzGxUt",
	"p9zOVozV9PkgOj7bhElZmVEyWBDxI9QxrtFpirl5LT2eRLxZ/E04mWV0SmKRPWJx0owCm64uiWWyNaHx",
	"1h9acS+/t3QVVe7UKvKpMO5HhcyfCFszSfk2pR3ZAGZ7K75m7kf8Mzk320Wqu2sf+uB7qmHrEtRPEftG",
	"QCZARTtsH36V4QB6CzdvE88qLVxeLLsWmuJbrMfvw9MPAHcJZNWTyGtXlo5Yb7p8w2PfiegCuutrjbhW",
	"/jHrs+/5vbQ1zcxFGiaSLaJx8gJazPgD/khQZiYxjuxo67ID1mVPIbORW67eQOxr9TOQhAQ0PID2yof8",
	"EzHxfdZnu+wJNEXBNtOubvFg+YZ3w2Nfscf812I7knWCNYJ9XTT1w3d1xP7C/m26ccMrIfaFCru6ssdO",
	"8O8ZpGGa2CXOORySMoz7vQCefBt+unbt2rXSxYul8+dNeTdhZCgnRo+N5bJclIt9Fwd3fFs1/6nQDuZb",
	"uLSApnIgbFo+Nvq2AuSVxDF/D3uUYeMeGrqGgKb4x5k7DMRT836Z7ZVAbI9/xj9lfb7B78UVygY6h5tt",
	"UjrnezTwHXQKvX0Vt0y0uFK65HukdBHTZhv97ZPfopnqLJoCHmXSYqpg6dqW5ZBf4oBkFs4hf8Fh6Ifc",
	"h7AXaOCfx1VS2e0JfI6Lofxh8vPUD9/V5sTESe9ewwAVQguXFw3TuBNXK1WJct00/A7xcMc2GsaM6qvo",
	"YNoGu1Bppji9JCEnfN8iAGiEFYXfBHg2LtghLeD60Bjq865Xqy+tv1Tfi6frN/3jSKUVHDgtadItldBe",
	"SZq/wYbGzuWoqQspj5xJEAeEBRAX+FgENMZNMXMl7rdJuDzc6swG0NG6pwLHQ5hwRxXFP5dVc7YDdfP7",
	"aXq1y++jKdqqBFGFeBUcoFMouSYCsSnYzcTsgYF8BJeW4F6AVC5hPJ7ze2yfP1Stxr2cYufunkgh1MiI",
	"3GD+mtL1YidBmj2WC8Omwbj9Z5z1/WHfRPJTnO2V36gk8Q/70yNugsQfUzlz8d0LCpzV1O2J5LMmMtNL",
	"S7qjSu5S0QTj5b2PSSaW/WUTjBy6+LV+81WqYtydp9O+b1QTtrDGGXERSrBuGrOTaF/meoh4pH52/CPZ",
	"GwgvquQZpeujpKlcs59UqZUeZ5W64sms/mjlnsAXgF/rykuBel8gfgI/ICFAuaCFPyU0W18oaOI4UY1v",
	"SE0i1vEtozdMXrP714nsI/DbT1iXPYObOM8yB31Soa3Ojn8kuc7zohJ71AbGpByPkuA1mehcH4kCfkpO",
	"JlSZ+55voGnTysjv8gLxOk/3K9UqlxHKUeeW9ByPPC454lVyUK6g4+GX+qjrJaCyPoQeB8mloK4Azztx",
	"d7T4oAk3TcQ/FhGUMLVmZrimmTrLcLk/yfA4Km6sGR0/1Bl5CauIi23HRDDhPutBUALQrR9fRxwInFVG",
	"2fi7QPJQSyRiO+hdstpsY1sEiDCVvHy+y7oClYoBQzHSHuuhBdWBBKfbQG9BGI9uRNXqTBM6JOFPooN0",
	"skGSBLJdMu2KirvGXooEaXox1/O5EBpEZL0gw7WXTEHcVasT5W8L3a7qCtNTlXcYnNBxvJAifA3Xo/sx",
	"MI/v2wE9SkOSC3O6m4IinE1vE2aEPpbznNRXXPWCAYfIDFleVs7D9xlJyR3WrEZXvgXeqYSP5F9tPDNy",
	"dzFPxkGVJFORSSY9dv2m8DYZDsckyhc1aJg4AJ2GiAzFl9WlREAENQFPK50ohKxxJ6LaBF2PHfDtBopL",
	"JWsq17puImJb2Y+5skn5hnc5CtsqZNxjXfYErtU/y4SqCn4O+FaSY9rnD5NshggL+WdCQCRE3YvtLcSG",
	"/J4woQCND9QhjrK8OtOyRKiUFUHlK7IsuaLYRDZlVtv2ngDwrKieACO+YdK9cPlSWMrcJpYuRUQ7z1VA",
	"3ld9+ltSCEdKM2SoK9A+Fx4FR9J+wvD4IHLoFRkCSRZBG9vN5VdHpAhWZTJ9grdhyFJB2tE4l3/7wmxV",
	"U+F5pYh1qFVUf328yx+A2epmMs+sx3Ygg565UrHFeibiD6SK9yHV1APDdsi3p/8eHu0I0o9Mm/fQlBRd",
	"9Z6QDbB2j2IzXAFr1AfLDJLMetMZYZbdWlKUZb6ulDSC6WP536Xhlqo9CAAmL608SF4JJOMpxL5gf2Bf",
	"IAdTdAo5vodOobTeX77hsd/D/fbnKnt4iFYC3y2XqS8Tc2CjH8tj45+yHpqrCx8jjNGz8g1PVhP/EUfU",
	"b+gvzPc01+XFwaedKz1ZvDCRihYfJM/IfGf5hjdbr6NMn7okLZ5A0RA3l5lIHJ+OFHh7QZc9Bpf6iUqA",
	"wPy6REa2BW1cSnHkzfN8dQJBYeWhOLUYnbPDLCvUywoSYA1v2nEwrTi+V8kc26jX0MRvLjrum4qOeiHN",
	"y3oBzVEvg3lpL38pmGUo9+Ta/Z4lFSETsUHxPERwdqAsUQ/xzZj/I3iev5es4fvYW056xgg1nPCdScdp",
	"dh21HPRnTrxYrTrxYsUigwBvB2BRHiS1BaHQQ5e6hxsxdVQnzUonLOssWicnEtqjJiIyaaSaiMi4423U",
	"SSXtWBPC0EKj7quFCLqmRv07fwpO4XWlP2fr9UmwcHot6u9RGNDwZ6jOp6Kr3SH/DXhga1QRUAVylbWk",
	"r2N9JNCYrc7mPW0aXPL7CpxDhMa3QA8EIOnxX/NH8Rt0prRpJdjSc4UEVQEbsW/ZATtA0luX2JcyZzc9",
	"wjfHjXEFv6x5nV+2geVVYW7zRAHEG5SKjhk6QlPThpL/FyWKuNskT7pKgX4B9eQihj+F2C6/l0u/JtAc",
	"ItvgTixlUeBkXsSAO3Y5eRnDnRocbTqiUanAxeq2H9LGfHW+CkNuJouspe9JlLlscy0D52x4ZUXyjVLl",
	"zDeSxMwXMjY21m+u/18AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
