//go:build go1.22

// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CalculationMethodId.
const (
	Egypt             CalculationMethodId = "egypt"
	Karachi           CalculationMethodId = "karachi"
	MuslimWorldLeague CalculationMethodId = "muslimWorldLeague"
	NorthAmerica      CalculationMethodId = "northAmerica"
	Turkey            CalculationMethodId = "turkey"
	UmmAlQura         CalculationMethodId = "ummAlQura"
)

// Valid indicates whether the value is a known member of the CalculationMethodId enum.
func (e CalculationMethodId) Valid() bool {
	switch e {
	case Egypt:
		return true
	case Karachi:
		return true
	case MuslimWorldLeague:
		return true
	case NorthAmerica:
		return true
	case Turkey:
		return true
	case UmmAlQura:
		return true
	default:
		return false
	}
}

// Defines values for ConfirmationStatus.
const (
	Confirmed ConfirmationStatus = "confirmed"
	Expected  ConfirmationStatus = "expected"
)

// Valid indicates whether the value is a known member of the ConfirmationStatus enum.
func (e ConfirmationStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Expected:
		return true
	default:
		return false
	}
}

// Defines values for DeviceRegistrationPlatform.
const (
	Ios DeviceRegistrationPlatform = "ios"
)

// Valid indicates whether the value is a known member of the DeviceRegistrationPlatform enum.
func (e DeviceRegistrationPlatform) Valid() bool {
	switch e {
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeInternal        ErrorCode = "internal"
	ErrorCodeInvalidArgument ErrorCode = "invalid_argument"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeRateLimited     ErrorCode = "rate_limited"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
	ErrorCodeUnsupported     ErrorCode = "unsupported"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidArgument:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for IshaRuleType.
const (
	Angle               IshaRuleType = "angle"
	MinutesAfterMaghrib IshaRuleType = "minutesAfterMaghrib"
)

// Valid indicates whether the value is a known member of the IshaRuleType enum.
func (e IshaRuleType) Valid() bool {
	switch e {
	case Angle:
		return true
	case MinutesAfterMaghrib:
		return true
	default:
		return false
	}
}

// Defines values for Madhab.
const (
	Hanafi Madhab = "hanafi"
	Shafii Madhab = "shafii"
)

// Valid indicates whether the value is a known member of the Madhab enum.
func (e Madhab) Valid() bool {
	switch e {
	case Hanafi:
		return true
	case Shafii:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSource.
const (
	PrayerSourceCalculated PrayerSource = "calculated"
	PrayerSourceOfficial   PrayerSource = "official"
)

// Valid indicates whether the value is a known member of the PrayerSource enum.
func (e PrayerSource) Valid() bool {
	switch e {
	case PrayerSourceCalculated:
		return true
	case PrayerSourceOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PrayerSourceParam.
const (
	PrayerSourceParamAuto       PrayerSourceParam = "auto"
	PrayerSourceParamCalculated PrayerSourceParam = "calculated"
	PrayerSourceParamOfficial   PrayerSourceParam = "official"
)

// Valid indicates whether the value is a known member of the PrayerSourceParam enum.
func (e PrayerSourceParam) Valid() bool {
	switch e {
	case PrayerSourceParamAuto:
		return true
	case PrayerSourceParamCalculated:
		return true
	case PrayerSourceParamOfficial:
		return true
	default:
		return false
	}
}

// Defines values for PushSettingsEnvironment.
const (
	Production PushSettingsEnvironment = "production"
	Sandbox    PushSettingsEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the PushSettingsEnvironment enum.
func (e PushSettingsEnvironment) Valid() bool {
	switch e {
	case Production:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// AyahRef defines model for AyahRef.
type AyahRef struct {
	// Ayah Example: 255
	Ayah int `json:"ayah"`

	// Surah Example: 2
	Surah int `json:"surah"`
}

// CalculationMethod defines model for CalculationMethod.
type CalculationMethod struct {
	// FajrAngle Example: 18
	FajrAngle float64 `json:"fajrAngle"`

	// Id Идентификаторы строго совпадают с CalculationMethod в iOS
	Id   CalculationMethodId `json:"id"`
	Isha IshaRule            `json:"isha"`

	// Title Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Title LocalizedString `json:"title"`
}

// CalculationMethodId Идентификаторы строго совпадают с CalculationMethod в iOS
type CalculationMethodId string

// CalculationMethodList defines model for CalculationMethodList.
type CalculationMethodList struct {
	Items []CalculationMethod `json:"items"`
}

// City defines model for City.
type City struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country              string `json:"country"`
	HasOfficialTimetable bool   `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// CityList defines model for CityList.
type CityList struct {
	Items      []City  `json:"items"`
	NextCursor *string `json:"nextCursor"`
}

// Config defines model for Config.
type Config struct {
	// ContentVersions Версии контента (quran, quranEditions, hadith, cities)
	//
	// Example: {"cities":7,"hadith":2,"quran":3,"quranEditions":5}
	ContentVersions map[string]int `json:"contentVersions"`
	Features        Features       `json:"features"`

	// LatestVersion Example: 1.0.3
	LatestVersion string `json:"latestVersion"`

	// MinSupportedVersion Example: 1.0.0
	MinSupportedVersion string          `json:"minSupportedVersion"`
	Ramadan             *RamadanSummary `json:"ramadan,omitempty"`

	// SupportUrl Example: https://namoz.tj/support
	SupportUrl string `json:"supportUrl"`
}

// ConfirmationStatus defines model for ConfirmationStatus.
type ConfirmationStatus string

// Coordinate defines model for Coordinate.
type Coordinate struct {
	// Latitude Example: 40.2826
	Latitude float64 `json:"latitude"`

	// Longitude Example: 69.6222
	Longitude float64 `json:"longitude"`
}

// Daily defines model for Daily.
type Daily struct {
	// Ayah Ссылка на аят; текст и перевод приложение берёт из своего Корана
	Ayah *DailyAyah `json:"ayah,omitempty"`

	// Date Example: 2026-10-03
	Date openapi_types.Date `json:"date"`

	// Reminder Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Reminder *LocalizedString `json:"reminder,omitempty"`
}

// DailyAyah Ссылка на аят; текст и перевод приложение берёт из своего Корана
type DailyAyah struct {
	Ref AyahRef `json:"ref"`
}

// DailyList defines model for DailyList.
type DailyList struct {
	Items []Daily `json:"items"`
}

// DailyReminder defines model for DailyReminder.
type DailyReminder struct {
	Day int `json:"day"`

	// Text Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Text LocalizedString `json:"text"`
}

// DeviceCreated defines model for DeviceCreated.
type DeviceCreated struct {
	// DeviceId Example: dev_5f1c0a9e3b7d4c2a8e6f1b0d
	DeviceId string `json:"deviceId"`

	// Token Секрет устройства. Показывается один раз, на сервере хранится только хэш.
	Token string `json:"token"`
}

// DeviceRegistration defines model for DeviceRegistration.
type DeviceRegistration struct {
	// AppVersion Example: 1.0.0
	AppVersion string `json:"appVersion"`

	// Country Example: TJ
	Country *string `json:"country,omitempty"`

	// Locale Example: ru_TJ
	Locale   *string                    `json:"locale,omitempty"`
	Platform DeviceRegistrationPlatform `json:"platform"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId *string `json:"timeZoneId,omitempty"`
}

// DeviceRegistrationPlatform defines model for DeviceRegistration.Platform.
type DeviceRegistrationPlatform string

// Dua defines model for Dua.
type Dua struct {
	Arabic string `json:"arabic"`

	// Id Example: iftar
	Id string `json:"id"`

	// Source Example: Sunan Abi Dawud 2357
	Source *string `json:"source,omitempty"`

	// Translations Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Translations    LocalizedString `json:"translations"`
	Transliteration *string         `json:"transliteration,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    ErrorCode               `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Example: City not found
	Message string `json:"message"`

	// RequestId Example: 01J9ZK3M5Q8T2V4X6Y8Z0A1B2C
	RequestId string `json:"requestId"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Features defines model for Features.
type Features struct {
	OfficialTimetables bool `json:"officialTimetables"`
	QuranSearch        bool `json:"quranSearch"`
	Sync               bool `json:"sync"`
}

// HijriDate defines model for HijriDate.
type HijriDate struct {
	// Day Example: 18
	Day int `json:"day"`

	// Month Example: 4
	Month int `json:"month"`

	// MonthName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	MonthName *LocalizedString `json:"monthName,omitempty"`

	// Year Example: 1448
	Year int `json:"year"`
}

// HijriMonthList defines model for HijriMonthList.
type HijriMonthList struct {
	Items []HijriMonthStart `json:"items"`
}

// HijriMonthStart defines model for HijriMonthStart.
type HijriMonthStart struct {
	// Month Example: 9
	Month int `json:"month"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// IshaRule defines model for IshaRule.
type IshaRule struct {
	Type IshaRuleType `json:"type"`

	// Value Example: 17
	Value float64 `json:"value"`
}

// IshaRuleType defines model for IshaRule.Type.
type IshaRuleType string

// LocalizedString Локализуемая строка. Ключи — коды языков.
//
// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
type LocalizedString struct {
	Ar *string `json:"ar,omitempty"`
	En *string `json:"en,omitempty"`
	Ru *string `json:"ru,omitempty"`
	Tg *string `json:"tg,omitempty"`
}

// Madhab defines model for Madhab.
type Madhab string

// NearestCity defines model for NearestCity.
type NearestCity struct {
	Coordinate Coordinate `json:"coordinate"`

	// Country Example: TJ
	Country string `json:"country"`

	// DistanceKm Example: 2.4
	DistanceKm           float64 `json:"distanceKm"`
	HasOfficialTimetable bool    `json:"hasOfficialTimetable"`

	// Id Example: khujand
	Id string `json:"id"`

	// Name Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Name LocalizedString `json:"name"`

	// Population Example: 183000
	Population *int `json:"population,omitempty"`

	// Region Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Region          *LocalizedString `json:"region,omitempty"`
	SuggestedMadhab Madhab           `json:"suggestedMadhab"`

	// SuggestedMethod Идентификаторы строго совпадают с CalculationMethod в iOS
	SuggestedMethod CalculationMethodId `json:"suggestedMethod"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`
}

// PrayerDay defines model for PrayerDay.
type PrayerDay struct {
	// Date Example: 2026-09-30
	Date  openapi_types.Date `json:"date"`
	Hijri HijriDate          `json:"hijri"`

	// Imsak Example: 2026-09-30T04:41:00+05:00
	Imsak *time.Time `json:"imsak,omitempty"`

	// Times Моменты времени в ISO 8601 со смещением часового пояса города
	Times PrayerTimes `json:"times"`
}

// PrayerSource defines model for PrayerSource.
type PrayerSource string

// PrayerSourceParam defines model for PrayerSourceParam.
type PrayerSourceParam string

// PrayerTimes Моменты времени в ISO 8601 со смещением часового пояса города
type PrayerTimes struct {
	// Asr Example: 2026-09-30T16:26:00+05:00
	Asr time.Time `json:"asr"`

	// Dhuhr Example: 2026-09-30T12:17:00+05:00
	Dhuhr time.Time `json:"dhuhr"`

	// Fajr Example: 2026-09-30T04:51:00+05:00
	Fajr time.Time `json:"fajr"`

	// Isha Example: 2026-09-30T19:33:00+05:00
	Isha time.Time `json:"isha"`

	// Maghrib Example: 2026-09-30T18:11:00+05:00
	Maghrib time.Time `json:"maghrib"`

	// Sunrise Example: 2026-09-30T06:20:00+05:00
	Sunrise time.Time `json:"sunrise"`
}

// PrayerTimesResponse defines model for PrayerTimesResponse.
type PrayerTimesResponse struct {
	// CityId null, если запрос был по координатам
	//
	// Example: dushanbe
	CityId *string     `json:"cityId,omitempty"`
	Days   []PrayerDay `json:"days"`
	Madhab Madhab      `json:"madhab"`

	// Method Идентификаторы строго совпадают с CalculationMethod в iOS
	Method CalculationMethodId `json:"method"`
	Source PrayerSource        `json:"source"`

	// SourceName Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	SourceName *LocalizedString `json:"sourceName,omitempty"`

	// TimeZoneId Example: Asia/Dushanbe
	TimeZoneId string `json:"timeZoneId"`

	// UpdatedAt Example: 2026-09-01T00:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PushSettings defines model for PushSettings.
type PushSettings struct {
	// ApnsToken Токен APNs (hex)
	ApnsToken   string                  `json:"apnsToken"`
	Environment PushSettingsEnvironment `json:"environment"`

	// Topics Example: ["ramadan-TJ","eid-TJ","announcements"]
	Topics []string `json:"topics"`
}

// PushSettingsEnvironment defines model for PushSettings.Environment.
type PushSettingsEnvironment string

// Ramadan defines model for Ramadan.
type Ramadan struct {
	ConfirmedAt *time.Time `json:"confirmedAt,omitempty"`

	// Country Example: TJ
	Country        string          `json:"country"`
	DailyReminders []DailyReminder `json:"dailyReminders"`
	Duas           []Dua           `json:"duas"`

	// EidAlFitr Example: 2027-03-10
	EidAlFitr openapi_types.Date `json:"eidAlFitr"`

	// EndDate Example: 2027-03-09
	EndDate openapi_types.Date `json:"endDate"`

	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// LaylatAlQadrExpected Example: 2027-03-05
	LaylatAlQadrExpected *openapi_types.Date `json:"laylatAlQadrExpected,omitempty"`

	// Length Example: 30
	Length int `json:"length"`

	// Source Локализуемая строка. Ключи — коды языков.
	//
	// Example: {"ar":"خجند","en":"Khujand","ru":"Худжанд","tg":"Хуҷанд"}
	Source *LocalizedString `json:"source,omitempty"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// RamadanSummary defines model for RamadanSummary.
type RamadanSummary struct {
	// HijriYear Example: 1448
	HijriYear int `json:"hijriYear"`

	// StartDate Example: 2027-02-08
	StartDate openapi_types.Date `json:"startDate"`
	Status    ConfirmationStatus `json:"status"`
}

// AcceptLanguage Example: ru
type AcceptLanguage = string

// CityIdPath Example: dushanbe
type CityIdPath = string

// CountryQuery Example: TJ
type CountryQuery = string

// CountryRequired Example: TJ
type CountryRequired = string

// Cursor defines model for Cursor.
type Cursor = string

// LatQuery defines model for LatQuery.
type LatQuery = float64

// Limit defines model for Limit.
type Limit = int

// LonQuery defines model for LonQuery.
type LonQuery = float64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unsupported defines model for Unsupported.
type Unsupported = Error

// ListCitiesParams defines parameters for ListCities.
type ListCitiesParams struct {
	// Query Строка поиска («Худж», «Хуҷанд», «Khujand»)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Country Код страны ISO 3166-1 alpha-2
	Country *CountryQuery `form:"country,omitempty" json:"country,omitempty"`
	Limit   *Limit        `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор из nextCursor предыдущего ответа
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetNearestCityParams defines parameters for GetNearestCity.
type GetNearestCityParams struct {
	Lat LatQuery `form:"lat" json:"lat"`
	Lon LonQuery `form:"lon" json:"lon"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetCityParams defines parameters for GetCity.
type GetCityParams struct {
	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetDailyParams defines parameters for GetDaily.
type GetDailyParams struct {
	// Date Один день (вместо from/to)
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Не больше 31 дня от from
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetHijriMonthsParams defines parameters for GetHijriMonths.
type GetHijriMonthsParams struct {
	// Country Код страны ISO 3166-1 alpha-2
	Country CountryRequired `form:"country" json:"country"`

	// Year Год хиджры
	Year int `form:"year" json:"year"`
}

// GetPrayerTimesParams defines parameters for GetPrayerTimes.
type GetPrayerTimesParams struct {
	// CityId Идентификатор города. Обязателен, если не переданы lat/lon/timeZoneId.
	CityId *string  `form:"cityId,omitempty" json:"cityId,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Lon    *float64 `form:"lon,omitempty" json:"lon,omitempty"`

	// TimeZoneId IANA часовой пояс, обязателен вместе с lat/lon
	TimeZoneId *string            `form:"timeZoneId,omitempty" json:"timeZoneId,omitempty"`
	From       openapi_types.Date `form:"from" json:"from"`
	To         openapi_types.Date `form:"to" json:"to"`

	// Method По умолчанию — suggestedMethod города
	Method *CalculationMethodId `form:"method,omitempty" json:"method,omitempty"`

	// Madhab По умолчанию — suggestedMadhab города
	Madhab *Madhab            `form:"madhab,omitempty" json:"madhab,omitempty"`
	Source *PrayerSourceParam `form:"source,omitempty" json:"source,omitempty"`
}

// GetRamadanParams defines parameters for GetRamadan.
type GetRamadanParams struct {
	// Country Код страны ISO 3166-1 alpha-2
	Country CountryRequired `form:"country" json:"country"`

	// AcceptLanguage Язык UI-текстов (tg, ru, en, ar). Фолбэк — en.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistration

// SetDevicePushJSONRequestBody defines body for SetDevicePush for application/json ContentType.
type SetDevicePushJSONRequestBody = PushSettings

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(w http.ResponseWriter, r *http.Request)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(w http.ResponseWriter, r *http.Request, params ListCitiesParams)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(w http.ResponseWriter, r *http.Request, params GetNearestCityParams)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(w http.ResponseWriter, r *http.Request, cityId CityIdPath, params GetCityParams)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// GetDaily Аят дня и напоминание дня
	// (GET /daily)
	GetDaily(w http.ResponseWriter, r *http.Request, params GetDailyParams)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// DeleteDevice Удалить устройство и все его данные
	// (DELETE /devices/me)
	DeleteDevice(w http.ResponseWriter, r *http.Request)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(w http.ResponseWriter, r *http.Request)
	// GetHijriMonths Начала месяцев хиджры по стране (подтверждённые/ожидаемые)
	// (GET /hijri/months)
	GetHijriMonths(w http.ResponseWriter, r *http.Request, params GetHijriMonthsParams)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(w http.ResponseWriter, r *http.Request, params GetPrayerTimesParams)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(w http.ResponseWriter, r *http.Request, hijriYear int, params GetRamadanParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCalculationMethods operation middleware
func (siw *ServerInterfaceWrapper) ListCalculationMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalculationMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCities operation middleware
func (siw *ServerInterfaceWrapper) ListCities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCitiesParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNearestCity operation middleware
func (siw *ServerInterfaceWrapper) GetNearestCity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearestCityParams

	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNearestCity(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCity operation middleware
func (siw *ServerInterfaceWrapper) GetCity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cityId" -------------
	var cityId CityIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "cityId", r.PathValue("cityId"), &cityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cityId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCityParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCity(w, r, cityId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDaily operation middleware
func (siw *ServerInterfaceWrapper) GetDaily(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDaily(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDevicePush operation middleware
func (siw *ServerInterfaceWrapper) SetDevicePush(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDevicePush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHijriMonths operation middleware
func (siw *ServerInterfaceWrapper) GetHijriMonths(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHijriMonthsParams

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Required query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "year", r.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHijriMonths(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrayerTimes operation middleware
func (siw *ServerInterfaceWrapper) GetPrayerTimes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPrayerTimesParams

	// ------------- Optional query parameter "cityId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cityId", r.URL.Query(), &params.CityId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cityId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cityId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "timeZoneId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeZoneId", r.URL.Query(), &params.TimeZoneId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "timeZoneId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeZoneId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", r.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "madhab" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "madhab", r.URL.Query(), &params.Madhab, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "madhab"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "madhab", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrayerTimes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRamadan operation middleware
func (siw *ServerInterfaceWrapper) GetRamadan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hijriYear" -------------
	var hijriYear int

	err = runtime.BindStyledParameterWithOptions("simple", "hijriYear", r.PathValue("hijriYear"), &hijriYear, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hijriYear", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRamadanParams

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRamadan(w, r, hijriYear, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/config", wrapper.GetConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities", wrapper.ListCities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities/nearest", wrapper.GetNearestCity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cities/{cityId}", wrapper.GetCity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/calculation-methods", wrapper.ListCalculationMethods)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/prayer-times", wrapper.GetPrayerTimes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ramadan/{hijriYear}", wrapper.GetRamadan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hijri/months", wrapper.GetHijriMonths)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/devices/me", wrapper.DeleteDevice)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/devices/me/push", wrapper.SetDevicePush)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/daily", wrapper.GetDaily)

	return m
}

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedResponseHeaders struct {
	RetryAfter *int
}
type RateLimitedJSONResponse struct {
	Body Error

	Headers RateLimitedResponseHeaders
}

type UnauthorizedJSONResponse Error

type UnsupportedJSONResponse Error

type ListCalculationMethodsRequestObject struct {
}

type ListCalculationMethodsResponseObject interface {
	VisitListCalculationMethodsResponse(w http.ResponseWriter) error
}

type ListCalculationMethods200JSONResponse CalculationMethodList

func (response ListCalculationMethods200JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCalculationMethods500JSONResponse struct{ InternalJSONResponse }

func (response ListCalculationMethods500JSONResponse) VisitListCalculationMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCitiesRequestObject struct {
	Params ListCitiesParams
}

type ListCitiesResponseObject interface {
	VisitListCitiesResponse(w http.ResponseWriter) error
}

type ListCities200JSONResponse CityList

func (response ListCities200JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities400JSONResponse struct{ BadRequestJSONResponse }

func (response ListCities400JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListCities429JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListCities500JSONResponse struct{ InternalJSONResponse }

func (response ListCities500JSONResponse) VisitListCitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCityRequestObject struct {
	Params GetNearestCityParams
}

type GetNearestCityResponseObject interface {
	VisitGetNearestCityResponse(w http.ResponseWriter) error
}

type GetNearestCity200JSONResponse NearestCity

func (response GetNearestCity200JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity400JSONResponse struct{ BadRequestJSONResponse }

func (response GetNearestCity400JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetNearestCity404JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestCity500JSONResponse struct{ InternalJSONResponse }

func (response GetNearestCity500JSONResponse) VisitGetNearestCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCityRequestObject struct {
	CityId CityIdPath `json:"cityId"`
	Params GetCityParams
}

type GetCityResponseObject interface {
	VisitGetCityResponse(w http.ResponseWriter) error
}

type GetCity200JSONResponse City

func (response GetCity200JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCity404JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCity500JSONResponse struct{ InternalJSONResponse }

func (response GetCity500JSONResponse) VisitGetCityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfig500JSONResponse struct{ InternalJSONResponse }

func (response GetConfig500JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetDailyRequestObject struct {
	Params GetDailyParams
}

type GetDailyResponseObject interface {
	VisitGetDailyResponse(w http.ResponseWriter) error
}

type GetDaily200JSONResponse DailyList

func (response GetDaily200JSONResponse) VisitGetDailyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDaily400JSONResponse struct{ BadRequestJSONResponse }

func (response GetDaily400JSONResponse) VisitGetDailyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDaily500JSONResponse struct{ InternalJSONResponse }

func (response GetDaily500JSONResponse) VisitGetDailyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice201JSONResponse DeviceCreated

func (response RegisterDevice201JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice500JSONResponse struct{ InternalJSONResponse }

func (response RegisterDevice500JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceRequestObject struct {
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteDevice401JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDevice500JSONResponse struct{ InternalJSONResponse }

func (response DeleteDevice500JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePushRequestObject struct {
	Body *SetDevicePushJSONRequestBody
}

type SetDevicePushResponseObject interface {
	VisitSetDevicePushResponse(w http.ResponseWriter) error
}

type SetDevicePush204Response struct {
}

func (response SetDevicePush204Response) VisitSetDevicePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetDevicePush400JSONResponse struct{ BadRequestJSONResponse }

func (response SetDevicePush400JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SetDevicePush401JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetDevicePush500JSONResponse struct{ InternalJSONResponse }

func (response SetDevicePush500JSONResponse) VisitSetDevicePushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonthsRequestObject struct {
	Params GetHijriMonthsParams
}

type GetHijriMonthsResponseObject interface {
	VisitGetHijriMonthsResponse(w http.ResponseWriter) error
}

type GetHijriMonths200JSONResponse HijriMonthList

func (response GetHijriMonths200JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonths400JSONResponse struct{ BadRequestJSONResponse }

func (response GetHijriMonths400JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetHijriMonths500JSONResponse struct{ InternalJSONResponse }

func (response GetHijriMonths500JSONResponse) VisitGetHijriMonthsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimesRequestObject struct {
	Params GetPrayerTimesParams
}

type GetPrayerTimesResponseObject interface {
	VisitGetPrayerTimesResponse(w http.ResponseWriter) error
}

type GetPrayerTimes200JSONResponse PrayerTimesResponse

func (response GetPrayerTimes200JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPrayerTimes400JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPrayerTimes404JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes422JSONResponse struct{ UnsupportedJSONResponse }

func (response GetPrayerTimes422JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetPrayerTimes429JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetPrayerTimes500JSONResponse struct{ InternalJSONResponse }

func (response GetPrayerTimes500JSONResponse) VisitGetPrayerTimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadanRequestObject struct {
	HijriYear int `json:"hijriYear"`
	Params    GetRamadanParams
}

type GetRamadanResponseObject interface {
	VisitGetRamadanResponse(w http.ResponseWriter) error
}

type GetRamadan200JSONResponse Ramadan

func (response GetRamadan200JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRamadan400JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRamadan404JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRamadan500JSONResponse struct{ InternalJSONResponse }

func (response GetRamadan500JSONResponse) VisitGetRamadanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListCalculationMethods Методы расчёта времени намазов
	// (GET /calculation-methods)
	ListCalculationMethods(ctx context.Context, request ListCalculationMethodsRequestObject) (ListCalculationMethodsResponseObject, error)
	// ListCities Поиск и список городов
	// (GET /cities)
	ListCities(ctx context.Context, request ListCitiesRequestObject) (ListCitiesResponseObject, error)
	// GetNearestCity Ближайший город по координатам
	// (GET /cities/nearest)
	GetNearestCity(ctx context.Context, request GetNearestCityRequestObject) (GetNearestCityResponseObject, error)
	// GetCity Один город
	// (GET /cities/{cityId})
	GetCity(ctx context.Context, request GetCityRequestObject) (GetCityResponseObject, error)
	// GetConfig Минимальная версия приложения, флаги, версии контента
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// GetDaily Аят дня и напоминание дня
	// (GET /daily)
	GetDaily(ctx context.Context, request GetDailyRequestObject) (GetDailyResponseObject, error)
	// RegisterDevice Регистрация анонимного устройства → токен
	// (POST /devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// DeleteDevice Удалить устройство и все его данные
	// (DELETE /devices/me)
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)
	// SetDevicePush APNs-токен и подписки на темы
	// (PUT /devices/me/push)
	SetDevicePush(ctx context.Context, request SetDevicePushRequestObject) (SetDevicePushResponseObject, error)
	// GetHijriMonths Начала месяцев хиджры по стране (подтверждённые/ожидаемые)
	// (GET /hijri/months)
	GetHijriMonths(ctx context.Context, request GetHijriMonthsRequestObject) (GetHijriMonthsResponseObject, error)
	// GetPrayerTimes Расписание намазов на диапазон дат
	// (GET /prayer-times)
	GetPrayerTimes(ctx context.Context, request GetPrayerTimesRequestObject) (GetPrayerTimesResponseObject, error)
	// GetRamadan Даты Рамадана и Ида по стране + дуа
	// (GET /ramadan/{hijriYear})
	GetRamadan(ctx context.Context, request GetRamadanRequestObject) (GetRamadanResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCalculationMethods operation middleware
func (sh *strictHandler) ListCalculationMethods(w http.ResponseWriter, r *http.Request) {
	var request ListCalculationMethodsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalculationMethods(ctx, request.(ListCalculationMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalculationMethods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCalculationMethodsResponseObject); ok {
		if err := validResponse.VisitListCalculationMethodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCities operation middleware
func (sh *strictHandler) ListCities(w http.ResponseWriter, r *http.Request, params ListCitiesParams) {
	var request ListCitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCities(ctx, request.(ListCitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCitiesResponseObject); ok {
		if err := validResponse.VisitListCitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNearestCity operation middleware
func (sh *strictHandler) GetNearestCity(w http.ResponseWriter, r *http.Request, params GetNearestCityParams) {
	var request GetNearestCityRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNearestCity(ctx, request.(GetNearestCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNearestCity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNearestCityResponseObject); ok {
		if err := validResponse.VisitGetNearestCityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCity operation middleware
func (sh *strictHandler) GetCity(w http.ResponseWriter, r *http.Request, cityId CityIdPath, params GetCityParams) {
	var request GetCityRequestObject

	request.CityId = cityId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCity(ctx, request.(GetCityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCityResponseObject); ok {
		if err := validResponse.VisitGetCityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDaily operation middleware
func (sh *strictHandler) GetDaily(w http.ResponseWriter, r *http.Request, params GetDailyParams) {
	var request GetDailyRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDaily(ctx, request.(GetDailyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDaily")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDailyResponseObject); ok {
		if err := validResponse.VisitGetDailyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request) {
	var request DeleteDeviceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetDevicePush operation middleware
func (sh *strictHandler) SetDevicePush(w http.ResponseWriter, r *http.Request) {
	var request SetDevicePushRequestObject

	var body SetDevicePushJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetDevicePush(ctx, request.(SetDevicePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetDevicePush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetDevicePushResponseObject); ok {
		if err := validResponse.VisitSetDevicePushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHijriMonths operation middleware
func (sh *strictHandler) GetHijriMonths(w http.ResponseWriter, r *http.Request, params GetHijriMonthsParams) {
	var request GetHijriMonthsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHijriMonths(ctx, request.(GetHijriMonthsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHijriMonths")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHijriMonthsResponseObject); ok {
		if err := validResponse.VisitGetHijriMonthsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPrayerTimes operation middleware
func (sh *strictHandler) GetPrayerTimes(w http.ResponseWriter, r *http.Request, params GetPrayerTimesParams) {
	var request GetPrayerTimesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPrayerTimes(ctx, request.(GetPrayerTimesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPrayerTimes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPrayerTimesResponseObject); ok {
		if err := validResponse.VisitGetPrayerTimesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRamadan operation middleware
func (sh *strictHandler) GetRamadan(w http.ResponseWriter, r *http.Request, hijriYear int, params GetRamadanParams) {
	var request GetRamadanRequestObject

	request.HijriYear = hijriYear
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRamadan(ctx, request.(GetRamadanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRamadan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRamadanResponseObject); ok {
		if err := validResponse.VisitGetRamadanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1HxbcxRHlvBfyahvHqSg+iohRH+xDzLYsxoDxgjPLgbWkepKqQvq0q4Lg0ahCEkYsEO2tdiOWAcz48t4",
	"J/ywGzuNUEOja4R/QeY+eV/9SzbyZNatK6u7JS5mX0BdlXXy5MlzPydzWWu6dtt1iBP4WmNZaxFsEA/+",
	"vEQCb2lmISAe/2UQv+mZ7cB0Ha2h0R9pl63SLn2K2BrdoQd0l33K/+c/u3SH3aH7dBvRPXpAn9B9eoDo",
	"IT2gW2ydHrBV2mPr7FNEn9IOPWSr9ICtabrmN1vExnyuYKlNtIZmOgFZJJ62srKia23sYZsEEreZZpO0",
	"g3PYWQzxIlHg93f6lG3QHfTebImtA0ZrfG66hcaCRR15oY6IoyPsjZcR/XeOP33EPqM76JfVrxBxypqu",
	"mRyQoIemaw62OU5i4lI8cxptchvbbYuP8kJNj1bhB57pLGp8DWfMYGnWuIiDFh8O8Nv8Rwy9CQM0XfPI",
	"h6HpEUNrBF5I1JMYod/CzjxRT+WGTuAtvRsSb0lBnof0gG4jThO2Sjt0n22g2bl30ERtaqpUQ9hqt3Cp",
	"HtHgQwCSIClAFyz98u80vllBQDz+7b9cnSm9f325vvKbQWheipf7kjAdhZ5HxDz0fFclGX+hXcHU9CnH",
	"mN3nONNniAsFW2VrXAAQ7dGnyCG3AwEGwRddus026Da7wz6hXfqYC80BW6dbtMvWaadojQIPhfikkD2H",
	"g5gTVEAsHAwk0oLr2TjgPOeG8xbnOBvfNu3Q1hqnq7pmm474UeK/5PROaM+D8OraOdM2g8K54WV6NoMs",
	"4NAKtMbJamqiejU9U03PawldO+c6g9fpOsddZ206s1D42b/SFQ7bb7uOT0BLvYENztnEh8U3XScgDvyJ",
	"223LbGLOMpUbPueb5RQWv/HIgtbQ/l8lUc0V8davvOl5rpxKwXdboJUlvx3SDojMHucftorGTOcWtkzj",
	"A+wthjZxgnFtRddmHc7v2HoFGH7DPqY9+oju0A6YCbYqEe5w3AQagNMFN3jLDR3jFeD0He2yNSGYiO7T",
	"Lv+nQ5/Rbdql+2jMcYMPFjgqgNclHBDgZfIqUPsWVMIW22AfAzJ0l/boHredGcspjJqHA/KBJXAb1/Sc",
	"HS/FhlyFjBxdSZl8wOg9B4dBy/XMP76SFf+FcyrXjbu0B7uRYWiw3ztACnZHGoQD+gwM+xbnoTCFLezX",
	"e44fttuu92r26xt6KLiZ3aM9tinZibs925yd2Cp9QnscU5DHNbapC2bj+9gDKV2FbzgJDthHtMfh0A54",
	"Vvv0AAwCgF+jh7TH1rg1hInGwmSd46AHJbLgKS3h1iW+nGWt7blt4gWmUE54CbcyBrB+8mReqeqaH3r9",
	"A5W6N9GqV+U3upjjejzcnb9BmgEHegZbzdAC+p8nQcs18vgt4BvejLNokczctWldoaX7FLGumcawfcxh",
	"MGvAh35rKAvM+i18KbQIHx+YgcBw0Afn3Ca2OFfOJSY5TS6Tu3wCkp5at8RmJPrNqnynr4UaY+u0x/mJ",
	"K17hgLMNFAvQY+G0H9AtbjHoNu2wz9k6YmsoNwmiW8h8Z07TNeJwK3hVs0PfMu1/cj3LOEfwYsiRdlwv",
	"aM3YxDObmA9dXGpz+x7a9oz1bujxZzexh5stk6869G6SpdQaI69FscZzpjCkWT4xA2Jn/zjStsMmiqmx",
	"5+Gl/OYAWOUmmMFSHp+m63qG6eBgKFucSUau6LGzelyfVNda2H9nYcFsmti6bNokwPOCNeXAede1CHYS",
	"8UimudkKb2DHUAEVntMR+VvX2m5bkrlPfCeq3I9zQssS6AkXLK92PLIoPz7izH64uEj8gBjnsdHC88Mg",
	"yFGZD2ONdAwFEpg2ed91yGwfiWd8E1fODgrZchoBSK+nopgUa2UmyuOeJ0MBexTx9QuRNS4fOfHStSTu",
	"4RAKWKGIMDBxBoZyCa6zYC6qhBNcgN8TzzddR9hBwzD5JmLrYmZoniX7tOsX3GKzNdrjzsoOPQBFK9Rt",
	"B419GHrY0RH896aYwddRCxtm0NJR0+TTcEct5pBlTTzUGqf4XvFxYGoBgtaYkH9FsLTGyRXFwhcIDkKP",
	"DN2bt6JxKzqP/ogf0STLtbVytTyhUgu26cxFPkfhl1XVlx62sYGHSvYlMWwutG3sLQn5hPne86zsTK0g",
	"aPuNSsXBtvvHcnCjIgdqKU8h9MyhMqdaUj9xUgTWc8yUQbGQKzlGpuvMBTgIYZsiW0put0mTu6oAmQ8k",
	"htowZixMlsG5QgpCI+s0TVbL9en61Eiek+U6i3kIU6fLU/V6fQQIfUSN8UlDVtHmLDatpWIvdRCrwKfc",
	"zwUhlWRJ+KNerU+VatVSdSLNEYbUojn2JLbpGMWh0qg+HcAvXOiMXFafSvmerbENugsRMo8NEO2wTbb+",
	"/1GSw0Rc2xzK7OsWJMdkBLELudYuDwp44PEI1NMDEVBBmpaPlnmlh5CG5QFEhzsYGZJ7IloYtPgoqOhf",
	"NP+kcM0vwqQILjm+ywbfX0ptcRYZAwMLxkmfiSEpJ10LyO3g+VmFG3eApMSZ3DKb5IxHsIxj+3CG1/3u",
	"hkFufXByodas4tNkYv6UMdms42kytVCbryrdvMC9SRwVRwLfrUJUqoq6y4h+C2F5BxLuqegWQeDb49E6",
	"57SnItrNJn66iN2VfNiTX0GUHxcT7rLP2Mfloao7pkG0kGI6XiKLph94sWvap27a7aNZs+f32i3OHaS/",
	"fvABwMgNbls44CosbTdM11eaiRfjicYz6mniKOkbYgVBPTxvNhVZ6XwQYi4E2FMt2ndDr9lHobnQwQ6a",
	"mTfRWfyH0ED1iZOnlHztYccXXrp/jGBCfG4GJGGYERx3uei+2VU0E9mkHNVI9HhoJuoN18jrP/F54Xzw",
	"jcI1NshIU57hA8EdDrBpDfChM/58goNNfF8W7ZL95LECctwAQbZVbZghk97PzdXa706///bE+ZPvTl+u",
	"/37yn6euTL9fnam9UT8zlLVhxQk+6SkKaXdGUikWvr6cuqZr6TQkpENkCln6dZbZFKOS3CR3ipP0LRR6",
	"ZFJeJddvpVz87Ba6/eGdrw7/IZCYI9hrttQD/CWnqXrTn+bjw3TVtNk5VNT8R/OGZ55V+rDSCmdyfnnL",
	"a7tOkM1LThYOu3C8JMYSwV4Wk8nJ6aHJT2HOBXoSRiEBzvNRL8IxSqDNBdgLnsNF6oeUQyxP+NPpOll9",
	"mMvkc7BnVW76qVK1XqpOj+Km+3H4NDjDlgu4clGf3KcEqxi4ijpx7jdHFjE00QxY5nBt0wkD4kNV5Txe",
	"bHnmvFKsb2Er7Mt1nzp6vAVvI2CqBfSzed7l+5P053Z53MDu0C7d42FIkjHeAbfvId1ln7P7tActE5AA",
	"2WYbiG2Kzgt6QLfK2fwGFybt5//6+T//597Pf4ckstbQ3o5Tj17IZ/8bu0O36RPwCbf5chfl0/9+Kp+t",
	"6DkfQ+lfEEf5mE+jeBwsqo17joBJWjHa6RZ28ILJ+aaFF0xTubsXCPaIH0QpY2xZ7yxojasjJdBy+tH0",
	"A+w0ydt2tixTnjw6v6Rg5bnl+oquXfTwEvHO4iWVnlaG2tXTpYnqKDLc4ppmJMV2VubITdvHN4umvFyd",
	"bEzWGtXqierJRjWHQYn7w1qBnzxUkwgyXIahylA/Wk4ETyV7Ashc4s5KBooMKPcQZFa5IPWThnARe9jO",
	"9EtoOAzcVHVG/jwq+MsRQfoUw5/pAd0TGU62gegWpCD2RMYB0S3oy5meqtagnMT/2aNdaGWBjATdQ+w+",
	"VC8PIBPxWDaFsU22RjuI/wbtsq1ISWDfK9z12lSjPnX0XTdaYWsA0HqjduroQBfwDW8Qe548BntGFUk1",
	"nqcbExNHh2lLO1QIdrpROwaqfuh4pk+KKTDVqFePCrZP2IDEyVTRRurAI8nKBtROU0x+SXbrKKIh0YmX",
	"EwIntCwd0S5bE00KqUYMRB+xDboLTC3sIWdoSIFA3bVD99L2MN2/N6QGonOfcnRfMFHZiuKLfcSqmP08",
	"xbAkch+Or1SL8VfH9NmPmfXQtbDNmdCYCdTsW61drnLebVSr7xdx7tFKWZkCnh3V7eyoXCdpJ/deycih",
	"35ojQWA6i74qleX4lwuyen+NO2lmLl7w0ViL3B5X0YQ4t0zPdWzZNRPZlbbnGmEzEAURHzvGvHtbnYJy",
	"22bTzxD0alQAKkGGi5iG+AM7jhs6TWJDJ/J1PWF1hfa6PSte1qtDwpyECNnFxKip6HopqVDlqoeiLCOY",
	"5Dg8MChjqJD6VLb6iEnyOMmt0AFGiI8ALcQqGMQ0Zqy3zMBTRXETpdpIHiBxjKJAcKJUPT2yE3lltEBd",
	"1yy8ZOFgxnoXG96bUb1NPfvJUWa3iLPYFwxPVJVB70iaUNXO8FpFywm1030JEnw2iI72NiZSmmckD+ZY",
	"fIA4RpVgRctAVkqPxhGvF31jSqYJnaCYJw+fnDRDzwyW5vg06ZrQcO0PlcGL78xdRpVbtYr4yo96sSHz",
	"x8PWVFK+FQRt0fxoOguuAvYD9pmAraxLsk10Aar0iH7PXSbwirboLrwV4QB6AzdvEscozVycLdsGGmPr",
	"tMvuwtf3we/inlVXeF7bonREu+Plaw79kUcXcLKk1og6Mj6iPfqY3UnaMvVMpKEj0R4dJS+gvZLdZw84",
	"Znoc44huzg7dox36FDIbmenqDUS/k68BJSjS7kFr8Sa7xwHfpT26TZ9A6x0sMznRwD8sX3OuOfQb+oh9",
	"Iqq3h/BuC8jXQWM//VhH9K/038Yb15wSol/LsKsj+ks5/Z5BGqaJbWKdwT4pw7ivuOPJNuDVlStXrpTO",
	"ny+dPauLczmFoRwfPTSWS1NRTPZjFNyxDdn4KkM7gDdzYQaNZZywcfFZ8UkdyCvxbX4MaxRh4w7qO4KD",
	"xthHqfM7xJFwH6Y7chDdYZ+xj2mPrbI7UYWygc7gZouUzrhO4LkWOoHevIwXdTS7ULrgOqR0HgfNFvrl",
	"3hdoojqJxoBGqbSYLFjapmFY5A/YI6mJM54/pzD0Au9C2As4sM+jKqnodAY6R8VQthm/Hvvpx9oUBxx3",
	"iDY0ECE0c3FW07VbUbVSlihXdM1tEwe3Ta2hTcjunTYOWqAXKs3ETy8JlxOeLxJwaLgWhXfcedbOmX6Q",
	"8+t9re+MQ71afWG91eqOT1Wv9Z8LhZZT4KTASTVVjHslPvgAOjQyLoNA51IeGZXANwhzR5z7xzyg0a5z",
	"yJWoqyumcn+bPz2Abu4dGTjuA8AtWRT/XPaBbEHd/G6SXu2wu2gsWKx4YYU4FeyhEyg+IgWxKejNWO2B",
	"gnwAB/bgTIwQLq48Dtkduss2ZZt9NyPYmXNXggkVPCIWmD2id1XR2xJnj8XEsGhQbv8RZX1/2tWR+BVl",
	"e8UTmST+aXe84BRU9DPhMxvfPieds5o8ORT/VkRmam5JVlTJHKgbYbw48zQKYNHFOMLIvkOPK9dfpihG",
	"PaAq6fteHkDg2jjFLlwIVnRtchTpSx2N4p/UTw//JH365nmFPCV0PRQfqFCsJxFqKcdpoa44IqtfLNwj",
	"2AKwax1xIFZtC/grsAPCBSjnpPC3JEjXF3KSOIxVo9OBo7B1dMLuNePX9PpVLPsA7PYT2qHP4BTas9RG",
	"H5dpq5PDP4mPsj0vxw5awJCU4yAOXhaJzpVCL+C35HhMlTrr/BqqNiWPfJlliFe5u9/IVrkUUxbtW9zZ",
	"XrhdYsTLpKCYQUXDh+qo6wV4ZT0IPfbiA3Ed7jxvRT34/Ici3NQR+4hHUFzV6qnhipb9NMHF+gTBjagx",
	"Wa3hv4nETZS8uRxuc38qcdlEiMY+FW4iyGVXhmx0C7HP4EjWOpJntT4tI+mn9R/gjWMiuGLhMZiofR4i",
	"vHf5DLh336ragMUNDHCocIs+ldYEzlby+Xa5g7kl+onZA7qNxhY8164E7riO2H3wgx9xP/gOJx2YxD0Z",
	"rXPggN0jOKTO46IDcW5xFw7Q7nOM/gYBcY+tIYmriAp5XBuFP0Cx6F6IA06TjOdKeyq387ckEJ3Aw5zO",
	"WK4kcdEY3ZKB+To9QNFiC7xKme5RXRZwlKZyrv9U4Pnsmvr4eSGc/IlZxHeA8xf7mHbRRC0mNWcqOYVq",
	"digNjz73y9TISXt4sUqJA/lDIWL7bJPuHdNyP5cm+lcuQzGRZRR4CJIh9IAUPBiQUipCj0idIjNtjWWt",
	"7foqtSJUALGxaeko0hiQ6IBwsBdpB77zm2WUzumpTgOk26y51nmbLDVb2HSuOenjBNu0Iw4MbPXnXXZo",
	"F83IrkbY4QZ6A1KD6FpYrU40oesa/iQqeRVN18QTLdhJp2XUifpiuCjf372Sza8GXkhWcnxce8EYRJ36",
	"Kl7+IddBLw/fPpW5zINfg6W/A3vSi4L96Pw64COtbnwAXXXy/pd7X6RO56d5XvJ5husrtrywxyIi657l",
	"lbPwPMUpmc2aVMjKD0A7mUQW9KsNJ0bmboPjUVAm3qXhSaXcr17n+jJF4QhFcfGRgogHINPgMqDokI7g",
	"CMjKjEDTSjv0oRLVDgNl0r9L99hGA0Xl12VZv1nRETGN9M9MKbZ8zbkY+i2ZhtqhHfoErql5lkp/yZCW",
	"+wFR3nqXbcYZUvBZwM0RYe9O5MNBvknlWxR4cyrVMkcCwSscy5ekWTKF9pF0yqTyKE0c1KdZ9Rhx52vG",
	"3TMXL/il1O0cwqRw9/RQJvl68uzPumDCQm6GqlcFWnL9QSFO0qPsHz0w7btySuFVfSnunErVbAp8qCVR",
	"oBvhdilRfky6pKeytxlNVhVV45fqc/W1n6uvY+mw+6C2OqlqFu3SLajKpY5prdNuFC9ATRECLa7Y9tnG",
	"+K9h0QagPrAU10VjgnXlvVuroO0eRGq4AtqoB5oZOJl2x1PMLDpABSuLGkApbi5VR49fJikcWc/kDpg4",
	"CHc/vmJP5GgQ/Zr+iX6NLBygE8hyHXQCJT1EPNz6Cu6LOZQViX3w/svlwBXJ/v3+WGGqDl4qj0TL1xzR",
	"ofAPOAzchvoCmq7i+hm+8Uk3XFcURHUkM1D3429EDaV8zZms11Hq7ItALQIgcYgaVnXEt0+FCtwGxGNP",
	"blLvyaQqwFfFium21mERY+GdKdmKJ4Ji7SbftTie30+TQl7+EzvWcHOdhYOK5TqV1LYVXesW3QR41Jv/",
	"Bl3w9qIudBt0udoLu0wtp5ahhJxpIX4WV5l1BJmKvv1AqWC/i9haRP+iiDhzo4aC7kNPTg6M80e5g/Ao",
	"DfRF00FgP/JkterIk+ULl9x52wONcj+uV3KB7ruOpL+5W4V13AB5zFLxrHF8JKHlciQk4+bMkZCMumiL",
	"dipu8RzRDc01/79cF0HVKK2+Qy9nFF5VSWWyXh/FF06OWv4axUYFffp6B2R0td1nv8EfWC9qLJCBXGU5",
	"7hVbKXQ0JquTWUubBJfsrnTO40T0Y+GQdNkn7EF0I92Y+pKJHixMprdFUwyiP9A9uoeEtS7Rh6IOMF5g",
	"m6Nm25xdVlyPm26Ke1k+t36sAOI1Km9FBC2Q1KRJ7f9E2TPqYMuiLlOgX0OPSt6HP4HoNruTKenErjlE",
	"tt6tiMtCz0pdIYTbZjm+RuhWDbY2GdGoVOCyhpbrB43p6nQVhlyPJ1lO7h0W9TF9OeXOmXDZUvxEinLq",
	"iUAx9UDExpkn4vqT6yv/GwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
